<?php $helper = $this->helper('mpanel') ?>
<?php if ($helper->acceptToUsePanel()): ?>
    <?php $template = $this->getRequest()->getParam('template') ?>
    <?php $block = $this->getRequest()->getParam('block') ?>
    <?php $currentCategoryId = $this->getRequest()->getParam('category_id') ?>
    <?php
    if ($this->getRequest()->getParam('category_id') && $this->getRequest()->getParam('product_id')) {
        $oRewrite = Mage::getModel('core/url_rewrite')
                ->setStoreId(Mage::app()->getStore()->getStoreId())
                ->getCollection()
                ->addFieldToFilter('category_id', array('eq' => $currentCategoryId))
                ->addFieldToFilter('product_id', array('eq' => $this->getRequest()->getParam('product_id')))
                ->getFirstItem();
    } else {
        $oRewrite = Mage::getModel('core/url_rewrite')
                ->setStoreId(Mage::app()->getStore()->getStoreId())
                ->getCollection()
                ->addFieldToFilter('category_id', array('eq' => $currentCategoryId))
                ->getFirstItem();
    }
    ?>
<div class="edit-static-form">
    <div class="row">
        <div class="col-md-12 builder-title">
            <h2>Select Block</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
                <div class="bs-glyphicons">
                    <ul class="bs-glyphicons-list" id="list-item">
                        <?php if ($this->getRequest()->getParam('category_id') && $this->getRequest()->getParam('product_id')): ?>
                        <li id="static-item" onclick="setLocation('<?php echo $this->getUrl('mpanel/index/formInCategory', array('template' => $template, 'block' => $block, 'type' => 'static', 'category_id' => $currentCategoryId, 'product_id' => $this->getRequest()->getParam('product_id'))) ?>')">
                            <span class="glyphicon glyphicon-text-width"></span>
                            <span class="glyphicon-class"><?php echo $this->__('Static Block') ?></span>
                        </li>  
                    <?php else: ?>
                        <li id="static-item" onclick="setLocation('<?php echo $this->getUrl('mpanel/index/formInCategory', array('template' => $template, 'block' => $block, 'type' => 'static', 'category_id' => $currentCategoryId)) ?>')">
                            <span class="glyphicon glyphicon-text-width"></span>
                            <span class="glyphicon-class"><?php echo $this->__('Static Block') ?></span>
                        </li>
                    <?php endif; ?>
                        <?php if ($this->getRequest()->getParam('category_id') && $this->getRequest()->getParam('product_id')): ?>
                            <li id="static-item" onclick="newInCategory('<?php echo $this->getUrl('mpanel/post/newInCategory', array('template' => $template, 'block' => $block, 'type' => 'core', 'category_id' => $currentCategoryId, 'core_block' => 'categoryNavigation', 'product_id' => $this->getRequest()->getParam('product_id'))) ?>')">
                                <span class="glyphicon glyphicon-list-alt"></span>
                                <span class="glyphicon-class"><?php echo $this->__('Category Navigation') ?></span>
                            </li>
                        <?php else: ?>
                            <li id="static-item" onclick="newInCategory('<?php echo $this->getUrl('mpanel/post/newInCategory', array('template' => $template, 'block' => $block, 'type' => 'core', 'category_id' => $currentCategoryId, 'core_block' => 'categoryNavigation')) ?>')">
                                <span class="glyphicon glyphicon-list-alt"></span>
                                <span class="glyphicon-class"><?php echo $this->__('Category Navigation') ?></span>
                            </li>
                        <?php endif; ?>
                        <?php if ($this->getRequest()->getParam('category_id') && !$this->getRequest()->getParam('product_id')): ?>
                            <li id="static-item" onclick="newInCategory('<?php echo $this->getUrl('mpanel/post/newInCategory', array('template' => $template, 'block' => $block, 'type' => 'core', 'category_id' => $currentCategoryId, 'core_block' => 'subCategories')) ?>')">
                                <span class="glyphicon glyphicon-list"></span>
                                <span class="glyphicon-class"><?php echo $this->__('Sub Categories') ?></span>
                            </li>
                        <?php endif; ?>
                        <?php if ($this->getRequest()->getParam('category_id') && !$this->getRequest()->getParam('product_id')): ?>
                            <li id="static-item" onclick="newInCategory('<?php echo $this->getUrl('mpanel/post/newInCategory', array('template' => $template, 'block' => $block, 'type' => 'core', 'category_id' => $currentCategoryId, 'core_block' => 'layeredNavigation')) ?>')">
                                <span class="glyphicon glyphicon-th"></span>
                                <span class="glyphicon-class"><?php echo $this->__('Layered Navigation') ?></span>
                            </li>
                        <?php endif; ?>
                        <?php if ($this->getRequest()->getParam('category_id') && $this->getRequest()->getParam('product_id')): ?>
                            <li id="static-item" onclick="newInCategory('<?php echo $this->getUrl('mpanel/post/newInCategory', array('template' => $template, 'block' => $block, 'type' => 'core', 'category_id' => $currentCategoryId, 'core_block' => 'cartSidebar', 'product_id' => $this->getRequest()->getParam('product_id'))) ?>')">
                                <span class="glyphicon glyphicon-shopping-cart"></span>
                                <span class="glyphicon-class"><?php echo $this->__('Cart Sidebar') ?></span>
                            </li>
                        <?php else: ?>
                            <li id="static-item" onclick="newInCategory('<?php echo $this->getUrl('mpanel/post/newInCategory', array('template' => $template, 'block' => $block, 'type' => 'core', 'category_id' => $currentCategoryId, 'core_block' => 'cartSidebar')) ?>')">
                                <span class="glyphicon glyphicon-shopping-cart"></span>
                                <span class="glyphicon-class"><?php echo $this->__('Cart Sidebar') ?></span>
                            </li>
                        <?php endif; ?>                        
                        <?php if ($this->getRequest()->getParam('category_id') && $this->getRequest()->getParam('product_id')): ?>
                            <li id="static-item" onclick="newInCategory('<?php echo $this->getUrl('mpanel/post/newInCategory', array('template' => $template, 'block' => $block, 'type' => 'core', 'category_id' => $currentCategoryId, 'core_block' => 'compareSidebar', 'product_id' => $this->getRequest()->getParam('product_id'))) ?>')">
                                <span class="glyphicon glyphicon-retweet"></span>
                                <span class="glyphicon-class"><?php echo $this->__('Compare Sidebar') ?></span>
                            </li>
                        <?php else: ?>
                            <li id="static-item" onclick="newInCategory('<?php echo $this->getUrl('mpanel/post/newInCategory', array('template' => $template, 'block' => $block, 'type' => 'core', 'category_id' => $currentCategoryId, 'core_block' => 'compareSidebar')) ?>')">
                                <span class="glyphicon glyphicon-retweet"></span>
                                <span class="glyphicon-class"><?php echo $this->__('Compare Sidebar') ?></span>
                            </li>
                        <?php endif; ?>                         
                        <?php if ($this->getRequest()->getParam('category_id') && $this->getRequest()->getParam('product_id')): ?>
                            <li id="static-item" onclick="newInCategory('<?php echo $this->getUrl('mpanel/post/newInCategory', array('template' => $template, 'block' => $block, 'type' => 'core', 'category_id' => $currentCategoryId, 'core_block' => 'reorderSidebar', 'product_id' => $this->getRequest()->getParam('product_id'))) ?>')">
                                <span class="glyphicon glyphicon-align-justify"></span>
                                <span class="glyphicon-class"><?php echo $this->__('Reorder Sidebar') ?></span>
                            </li>
                        <?php else: ?>
                            <li id="static-item" onclick="newInCategory('<?php echo $this->getUrl('mpanel/post/newInCategory', array('template' => $template, 'block' => $block, 'type' => 'core', 'category_id' => $currentCategoryId, 'core_block' => 'reorderSidebar')) ?>')">
                                <span class="glyphicon glyphicon-align-justify"></span>
                                <span class="glyphicon-class"><?php echo $this->__('Reorder Sidebar') ?></span>
                            </li>
                        <?php endif; ?>                        
                        <?php if ($this->getRequest()->getParam('category_id') && $this->getRequest()->getParam('product_id')): ?>
                            <li id="static-item" onclick="setLocation('<?php echo $this->getUrl('mpanel/index/poll', array('template' => $template, 'block' => $block, 'type' => 'core', 'category_id' => $currentCategoryId, 'product_id' => $this->getRequest()->getParam('product_id'))) ?>')">
                                <span class="glyphicon glyphicon-align-left"></span>
                                <span class="glyphicon-class"><?php echo $this->__('Poll') ?></span>
                            </li> 
                        <?php else: ?>
                            <li id="static-item" onclick="setLocation('<?php echo $this->getUrl('mpanel/index/poll', array('template' => $template, 'block' => $block, 'type' => 'core', 'category_id' => $currentCategoryId)) ?>')">
                                <span class="glyphicon glyphicon-align-left"></span>
                                <span class="glyphicon-class"><?php echo $this->__('Poll') ?></span>
                            </li> 
                        <?php endif; ?>   
                        <?php if ($this->getRequest()->getParam('category_id') && $this->getRequest()->getParam('product_id')): ?>
                            <li id="static-item" onclick="newInCategory('<?php echo $this->getUrl('mpanel/post/newInCategory', array('template' => $template, 'block' => $block, 'type' => 'core', 'category_id' => $currentCategoryId, 'core_block' => 'productViewed', 'product_id' => $this->getRequest()->getParam('product_id'))) ?>')">
                                <span class="glyphicon glyphicon-eye-open"></span>
                                <span class="glyphicon-class"><?php echo $this->__('Product Viewed') ?></span>
                            </li> 
                        <?php else: ?>
                            <li id="static-item" onclick="newInCategory('<?php echo $this->getUrl('mpanel/post/newInCategory', array('template' => $template, 'block' => $block, 'type' => 'core', 'category_id' => $currentCategoryId, 'core_block' => 'productViewed')) ?>')">
                                <span class="glyphicon glyphicon-eye-open"></span>
                                <span class="glyphicon-class"><?php echo $this->__('Product Viewed') ?></span>
                            </li>
                        <?php endif; ?>                                                                      
                        <?php if ($this->getRequest()->getParam('category_id') && $this->getRequest()->getParam('product_id')): ?>
                            <li id="static-item" onclick="newInCategory('<?php echo $this->getUrl('mpanel/post/newInCategory', array('template' => $template, 'block' => $block, 'type' => 'core', 'category_id' => $currentCategoryId, 'core_block' => 'wishlistSidebar', 'product_id' => $this->getRequest()->getParam('product_id'))) ?>')">
                                <span class="glyphicon glyphicon-heart"></span>
                                <span class="glyphicon-class"><?php echo $this->__('Wishlist Sidebar') ?></span>
                            </li> 
                        <?php else: ?>
                            <li id="static-item" onclick="newInCategory('<?php echo $this->getUrl('mpanel/post/newInCategory', array('template' => $template, 'block' => $block, 'type' => 'core', 'category_id' => $currentCategoryId, 'core_block' => 'wishlistSidebar')) ?>')">
                                <span class="glyphicon glyphicon-heart"></span>
                                <span class="glyphicon-class"><?php echo $this->__('Wishlist Sidebar') ?></span>
                            </li> 
                        <?php endif; ?>                        
                        <?php if ($this->getRequest()->getParam('category_id') && $this->getRequest()->getParam('product_id')): ?>
                            <li id="static-item" onclick="newInCategory('<?php echo $this->getUrl('mpanel/post/newInCategory', array('template' => $template, 'block' => $block, 'type' => 'core', 'category_id' => $currentCategoryId, 'core_block' => 'tagsPopular', 'product_id' => $this->getRequest()->getParam('product_id'))) ?>')">
                                <span class="glyphicon glyphicon-tags"></span>
                                <span class="glyphicon-class"><?php echo $this->__('Tags Popular') ?></span>
                            </li>
                        <?php else: ?>
                            <li id="static-item" onclick="newInCategory('<?php echo $this->getUrl('mpanel/post/newInCategory', array('template' => $template, 'block' => $block, 'type' => 'core', 'category_id' => $currentCategoryId, 'core_block' => 'tagsPopular')) ?>')">
                                <span class="glyphicon glyphicon-tags"></span>
                                <span class="glyphicon-class"><?php echo $this->__('Tags Popular') ?></span>
                            </li>
                        <?php endif; ?>                        
                        <?php if ($this->getRequest()->getParam('category_id') && $this->getRequest()->getParam('product_id')): ?>
                            <li id="static-item" onclick="newInCategory('<?php echo $this->getUrl('mpanel/post/newInCategory', array('template' => $template, 'block' => $block, 'type' => 'core', 'category_id' => $currentCategoryId, 'core_block' => 'newsletter', 'product_id' => $this->getRequest()->getParam('product_id'))) ?>')">
                                <span class="glyphicon glyphicon-envelope"></span>
                                <span class="glyphicon-class"><?php echo $this->__('Newsletter') ?></span>
                            </li>
                        <?php else: ?>
                            <li id="static-item" onclick="newInCategory('<?php echo $this->getUrl('mpanel/post/newInCategory', array('template' => $template, 'block' => $block, 'type' => 'core', 'category_id' => $currentCategoryId, 'core_block' => 'newsletter')) ?>')">
                                <span class="glyphicon glyphicon-envelope"></span>
                                <span class="glyphicon-class"><?php echo $this->__('Newsletter') ?></span>
                            </li>
                        <?php endif; ?>                        
                        <?php if ($this->getRequest()->getParam('product_id')): ?>
                            <li id="static-item" onclick="newInCategory('<?php echo $this->getUrl('mpanel/post/newInCategory', array('template' => $template, 'block' => $block, 'type' => 'core', 'category_id' => $currentCategoryId, 'core_block' => 'productRelated', 'product_id' => $this->getRequest()->getParam('product_id'))) ?>')">
                                <span class="glyphicon glyphicon-th"></span>
                                <span class="glyphicon-class"><?php echo $this->__('Product Related') ?></span>
                            </li>
                        <?php endif; ?>
                        <?php if ($this->getRequest()->getParam('category_id') && $this->getRequest()->getParam('product_id')): ?>
                            <li id="static-item" onclick="setLocation('<?php echo $this->getUrl('mpanel/index/promo', array('template' => $template, 'block' => $block, 'type' => 'core', 'category_id' => $currentCategoryId, 'product_id' => $this->getRequest()->getParam('product_id'))) ?>')">
                                <span class="glyphicon glyphicon-gift"></span>
                                <span class="glyphicon-class"><?php echo $this->__('Promo Banner') ?></span>
                            </li> 
                        <?php else: ?>
                            <li id="static-item" onclick="setLocation('<?php echo $this->getUrl('mpanel/index/promo', array('template' => $template, 'block' => $block, 'type' => 'core', 'category_id' => $currentCategoryId)) ?>')">
                                <span class="glyphicon glyphicon-gift"></span>
                                <span class="glyphicon-class"><?php echo $this->__('Promo Banner') ?></span>
                            </li> 
                        <?php endif; ?>
                    </ul>
            </div>
            <script type="text/javascript">
                function newInCategory(url) {
                    mgsjQuery.ajax({
                        type: 'POST',
                        url: url,
                        dataType: 'json',
                        success: function (data, textStatus, xhr) {
                            if (data.result == 'success') {                                
                                parent.mgsjQuery.magnificPopup.close();
                                window.top.location.reload();                                
                            }
                        }
                    });
                }
            </script>
        </div>
    </div>
</div>
<?php endif ?>

