<?php $helper = $this->helper('mpanel') ?>
<?php if($helper->acceptToUsePanel()): ?>
	<?php $template = $this->getRequest()->getParam('template') ?>
	<?php $block = $this->getRequest()->getParam('block') ?>
	<div class="edit-static-form">
	
		<div class="row">
			<div class="col-md-12 builder-title">
				<h2><?php echo $this->__('Select Block') ?></h2>
			</div>
		</div>
	
		<div class="row">
			<div class="col-md-12">
				<div class="bs-glyphicons">
					<ul class="bs-glyphicons-list" id="list-item">
						<li id="static-item" onclick="setLocation('<?php echo $this->getUrl('mpanel/index/form', array('template'=>$template, 'block'=>$block, 'type'=>'static')) ?>')">
							<span class="glyphicon glyphicon-text-width"></span>
							<span class="glyphicon-class"><?php echo $this->__('Text & Image') ?></span>
						</li>
						
						<li id="slider-item" onclick="setLocation('<?php echo $this->getUrl('mpanel/index/form', array('template'=>$template, 'block'=>$block, 'type'=>'revolution')) ?>')">
							<span class="glyphicon glyphicon-picture"></span>
							<span class="glyphicon-class"><?php echo $this->__('Revolution slider') ?></span>
						</li>
						
						<li id="new-item" onclick="setLocation('<?php echo $this->getUrl('mpanel/index/form', array('template'=>$template, 'block'=>$block, 'type'=>'new_products')) ?>')">
							<span class="glyphicon glyphicon-fire"></span>
							<span class="glyphicon-class"><?php echo $this->__('New Products') ?></span>
						</li>
						
						<?php if(Mage::getStoreConfig('mpanel/catalog/featured')!=''): ?>
							<li id="featured-item" onclick="setLocation('<?php echo $this->getUrl('mpanel/index/form', array('template'=>$template, 'block'=>$block, 'type'=>'featured_products')) ?>')">
								<span class="glyphicon glyphicon-flag"></span>
								<span class="glyphicon-class"><?php echo $this->__('Featured Products') ?></span>
							</li>
						<?php endif ?>
						
						<?php if(Mage::getStoreConfig('mpanel/catalog/hot')!=''): ?>
							<li id="hot-item" onclick="setLocation('<?php echo $this->getUrl('mpanel/index/form', array('template'=>$template, 'block'=>$block, 'type'=>'hot')) ?>')">
								<span class="glyphicon glyphicon-certificate"></span>
								<span class="glyphicon-class"><?php echo $this->__('Best Selling Products') ?></span>
							</li>
						<?php endif ?>
						
						<?php if(Mage::getStoreConfig('mpanel/catalog/brands')!=''): ?>
							<li id="brands-item" onclick="setLocation('<?php echo $this->getUrl('mpanel/index/form', array('template'=>$template, 'block'=>$block, 'type'=>'brands')) ?>')">
								<span class="glyphicon glyphicon-th"></span>
								<span class="glyphicon-class"><?php echo $this->__('Featured Brands') ?></span>
							</li>
						<?php endif ?>
						
						<?php if(Mage::getStoreConfig('deals/general/enabled')): ?>
							<li id="deals-item" onclick="setLocation('<?php echo $this->getUrl('mpanel/index/form', array('template'=>$template, 'block'=>$block, 'type'=>'deals')) ?>')">
								<span class="glyphicon glyphicon-tag"></span>
								<span class="glyphicon-class"><?php echo $this->__('Deals') ?></span>
							</li>
						<?php endif ?>
						
						<li id="tabs-item" onclick="setLocation('<?php echo $this->getUrl('mpanel/index/form', array('template'=>$template, 'block'=>$block, 'type'=>'tabs')) ?>')">
							<span class="glyphicon glyphicon-tasks"></span>
							<span class="glyphicon-class"><?php echo $this->__('Product Tabs') ?></span>
						</li>
						
						<li id="banner-item" onclick="setLocation('<?php echo $this->getUrl('mpanel/index/form', array('template'=>$template, 'block'=>$block, 'type'=>'promo_banner')) ?>')">
							<span class="glyphicon glyphicon-gift"></span>
							<span class="glyphicon-class"><?php echo $this->__('Promo Banner') ?></span>
						</li>
						
						<?php if($this->helper('core')->isModuleEnabled('AW_Blog') && Mage::getStoreConfig('blog/blog/enabled')): ?>
							<li id="post-item" onclick="setLocation('<?php echo $this->getUrl('mpanel/index/form', array('template'=>$template, 'block'=>$block, 'type'=>'latest_posts')) ?>')">
								<span class="glyphicon glyphicon-comment"></span>
								<span class="glyphicon-class"><?php echo $this->__('Latest Post') ?></span>
							</li>
						<?php endif ?>
						
						<li id="separator-item" onclick="setLocation('<?php echo $this->getUrl('mpanel/index/form', array('template'=>$template, 'block'=>$block, 'type'=>'separator')) ?>')">
							<span class="glyphicon glyphicon-resize-vertical"></span>
							<span class="glyphicon-class"><?php echo $this->__('Separator') ?></span>
						</li>
						
						<li id="category-item" onclick="setLocation('<?php echo $this->getUrl('mpanel/index/form', array('template'=>$template, 'block'=>$block, 'type'=>'category')) ?>')">
							<span class="glyphicon glyphicon-list-alt"></span>
							<span class="glyphicon-class"><?php echo $this->__('Category Navigation') ?></span>
						</li>
						
						<?php $categoryProductLayout = $helper->getCategoryProductLayout(); ?>
						<?php if(count($categoryProductLayout)>0): ?>
							<li id="category-product" onclick="setLocation('<?php echo $this->getUrl('mpanel/index/form', array('template'=>$template, 'block'=>$block, 'type'=>'category_products')) ?>')">
								<span class="glyphicon glyphicon-align-center"></span>
								<span class="glyphicon-class"><?php echo $this->__('Category Products') ?></span>
							</li>
						<?php endif ?>
						
						<?php if($this->helper('core')->isModuleEnabled('MGS_Testimonial')): ?>
							<li id="testimonials-item" onclick="setLocation('<?php echo $this->getUrl('mpanel/index/form', array('template'=>$template, 'block'=>$block, 'type'=>'testimonials')) ?>')">
								<span class="fa fa-quote-left"></span>&nbsp;&nbsp;&nbsp;<span class="fa fa-quote-right"></span>
								<span class="glyphicon-class"><?php echo $this->__('Testimonial') ?></span>
							</li>
						<?php endif ?>
					</ul>
				</div>
			</div>
		</div>
	</div>
<?php endif ?>

