<?php $brands = $this->getBrands(); ?>
<?php 
	if($this->getBrandCount()){
		$number = $this->getBrandCount();
	}
	else{
		$number = 5;
	}
?>
<?php if(count($brands)>0): ?>
	<div class="brands-container">
		<?php if($this->getSlider()==1): ?>
			<?php if($this->getTitle()): ?>
			<div class="carousel_wrapper">
				<div class="title">
					<h2><?php echo $this->getTitle() ?></h2>
				</div>
			</div>
			<?php endif; ?>
			<div class="brand-thumbnails clearfix">
				<ul id="brands-carousel" class="owl-carousel brands-carousel">
					<?php foreach($brands as $brand): ?>
						<li class="item">
							<div class="entry">
								<a href="<?php echo $brand->getContent()?>"><img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'abrands/'.$brand->getFilename() ?>" alt="<?php echo $brand->getTitle() ?>"></a>
							</div>
						</li>
					<?php endforeach ?>
				</ul>
			</div>
			<script type="text/javascript">
				initSlider('brands-carousel', <?php echo $number ?>, <?php echo $this->getAutoPlay()?>, <?php echo $this->getStopHover()?>, <?php echo $this->getNavigation()?>, <?php echo $this->getPagination()?>);
			</script>
		<?php else: ?>
			<?php foreach($brands as $brand): ?>
				<div class="col-md-2 col-sm-4 col-xs-6">
					<a href="<?php echo $brand->getContent()?>"><img style="margin-bottom: 42px;" class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'abrands/'.$brand->getFilename() ?>" alt="<?php echo $brand->getTitle() ?>"></a>
				</div>
			<?php endforeach ?>
		<?php endif ?>
	</div>
<?php endif ?>