<?php
/**
 * @var $this Qbikz_InformaxionSms_Block_Adminhtml_System_Config_Fieldset_Hint
 */
?>
<?php if ($this->getHelpLink()): ?>
<style type="text/css">
    .content-header{
        margin-bottom: 0px;
    }
</style>
<div class="imsms-notice">
    <a href="<?php echo $this->getHelpLink()?>" target="_blank" title="<?php echo $this->escapeHtml($this->__('Visit SMS Portal in new window'))?>" style="margin-left:0px;"><img src="https://www.smsalert.co.in/logo/www.smsalert.co.in.png" height="90px" /></a>
</div>
<?php endif; ?>