<?php $helper = $this->helper('mpanel') ?>
<div class="home-1column-full">
	<?php // Block 1 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 1) ?>>
		
			<div class="container">
				<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block1')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
			</div>

	</section>

	<?php // Block 2 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 2) ?>>
		<div class="container">
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block2')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
		</div>
	</section>

	<?php // Block 3 content ?>
	<!--section<?php echo $this->getBlockSetting('1_column_full', 3) ?>>
		<div class="container">
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block3')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
		</div>
	</section-->

	<?php // Block 4 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 4) ?>>
		<div class="container">
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block4')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
		</div>
	</section>
	
	<?php // Block 5 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 5) ?>>
		<div class="container">
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block5')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
		</div>
	</section>
	
	<?php // Block 6 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 6) ?>>
		<div class="container">
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block6')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
		</div>
	</section>
	
	<?php // Block 7 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 7) ?>>
		<div class="container">
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block7')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
		</div>
	</section>
	
	<?php // Block 8 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 8) ?>>
		<div class="container">
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block8')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
		</div>
	</section>
	
	<?php // Block 9 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 9) ?>>
		<div class="container">
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block9')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
		</div>
	</section>
	
	<?php // Block 10 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 10) ?>>
		<div class="container">
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block10')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
		</div>
	</section>
	
	<?php // Block 11 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 11) ?>>
		<div class="container">
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block11')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
		</div>
	</section>
	
	<?php // Block 12 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 12) ?>>
		<div class="container">
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block12')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
		</div>
	</section>
	
	<?php // Block 13 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 13) ?>>
		<div class="container">
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block13')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
		</div>
	</section>
	
	<?php // Block 14 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 14) ?>>
		<div class="container">
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block14')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
		</div>
	</section>
	
	<?php // Block 15 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 15) ?>>
		<div class="container">
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block15')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
		</div>
	</section>
</div>