<?php $helper = $this->helper('mpanel') ?>
<div class="home-2columns-right-1">
	<?php // Block 1 content ?>
	<section<?php echo $this->getBlockSetting('2_columns_right_1', 1) ?>>
			<div class="container">
				<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('2_columns_right_1')->setBlockName('block1')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
			</div>

	</section>

	<?php // Block 2 content ?>
	<section<?php echo $this->getBlockSetting('2_columns_right_1', 2) ?>>
		<div class="container">
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('2_columns_right_1')->setBlockName('block2')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
		</div>
	</section>

	<section>
		<div class="container">
			<div class="row">
				<?php // Block 3 content ?>
				<div<?php echo $this->getBlockSetting('2_columns_right_1', 3, 'col-md-9') ?>>
					<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('2_columns_right_1')->setBlockName('block3')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
				</div>
				
				<?php // Block 4 content ?>
				<div<?php echo $this->getBlockSetting('2_columns_right_1', 4, 'col-md-3') ?>>
					<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('2_columns_right_1')->setBlockName('block4')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
				</div>
			</div>
		</div>
	</section>

	<?php // Block 5 content ?>
	<section<?php echo $this->getBlockSetting('2_columns_right_1', 5) ?>>
		<div class="container">
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('2_columns_right_1')->setBlockName('block5')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
		</div>
	</section>
</div>