<?php $helper = $this->helper('mpanel') ?>
<div class="home-3columns-equal">
	<?php // Block 9 content ?>
	<section<?php echo $this->getBlockSetting('3_columns_equal', 9) ?>>
		<div class="container">
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('3_columns_equal')->setBlockName('block9')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
		</div>
	</section>
	
	<?php // Block 10 content ?>
	<section<?php echo $this->getBlockSetting('3_columns_equal', 10) ?>>
		<div class="container">
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('3_columns_equal')->setBlockName('block10')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
		</div>
	</section>
	
	<?php // Block 11 content ?>
	<section<?php echo $this->getBlockSetting('3_columns_equal', 11) ?>>
		<div class="container">
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('3_columns_equal')->setBlockName('block11')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
		</div>
	</section>
	
	<?php // Block 1 content ?>
	<section<?php echo $this->getBlockSetting('3_columns_equal', 1) ?>>
			<div class="container">
				<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('3_columns_equal')->setBlockName('block1')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
			</div>

	</section>

	<?php // Block 2 content ?>
	<section<?php echo $this->getBlockSetting('3_columns_equal', 2) ?>>
		<div class="container">
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('3_columns_equal')->setBlockName('block2')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
		</div>
	</section>

	<section<?php echo $this->getBlockSetting('3_columns_equal', 3) ?>>
		<div class="container">
			<div class="row">
				<?php // Block 3 content ?>
				<div class="col-md-4 section4">
					<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('3_columns_equal')->setBlockName('block3')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
				</div>
				
				<?php // Block 4 content ?>
				<div class="col-md-4 section5">
					<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('3_columns_equal')->setBlockName('block4')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
				</div>
				
				<?php // Block 5 content ?>
				<div class="col-md-4 section6">
					<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('3_columns_equal')->setBlockName('block5')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
				</div>
			</div>
		</div>
	</section>

	<?php // Block 6 content ?>
	<section<?php echo $this->getBlockSetting('3_columns_equal', 6) ?>>
		<div class="container">
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('3_columns_equal')->setBlockName('block6')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
		</div>
	</section>
	
	<?php // Block 7 content ?>
	<section<?php echo $this->getBlockSetting('3_columns_equal', 7) ?>>
		<div class="container">
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('3_columns_equal')->setBlockName('block7')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
		</div>
	</section>
	
	<?php // Block 8 content ?>
	<section<?php echo $this->getBlockSetting('3_columns_equal', 8) ?>>
		<div class="container">
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('3_columns_equal')->setBlockName('block8')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
		</div>
	</section>
	
	<?php // Block 12 content ?>
	<section<?php echo $this->getBlockSetting('3_columns_equal', 12) ?>>
		<div class="container">
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('3_columns_equal')->setBlockName('block12')->setTemplate('mgs/mpanel/template/child.phtml')->toHtml() ?>
		</div>
	</section>
</div>