<?php $helper = $this->helper('mpanel') ?>
<?php $templateLayout = $this->getTemplateLayout() ?>
<?php $blockName = $this->getBlockName() ?>
<?php $blocks = $this->getChildBlocks() ?>
<div class="row">
	<?php if(count($blocks)>0): ?>
		<?php foreach($blocks as $_block): ?>
			<?php $setting = json_decode($_block->getSetting(), true) ?>
			<div class="col-md-<?php echo $_block->getCol() ?><?php if($_block->getCol()<=3): ?> col-sm-6 col-xs-12<?php endif ?><?php if(isset($setting['custom_class']) && $setting['custom_class']!=''): ?> <?php echo $setting['custom_class'] ?><?php endif ?>"<?php if(isset($setting['animation']) && $setting['animation']!=''): ?> data-appear-animation="<?php echo $setting['animation'] ?>"<?php endif ?><?php if(isset($setting['animation_delay']) && $setting['animation_delay']!=''): ?> data-appear-animation-delay="<?php echo $setting['animation_delay'] ?>"<?php endif ?>>
				<?php echo $helper->getContentOfBlock($_block) ?>
			</div>
		<?php endforeach ?>
	<?php endif ?>
</div>