<?php if (($_products = $this->getSpecialProducts('featured')) && (count($_products)>0)): ?>
	<?php $helper = $this->helper('mpanel') ?>
	<?php $size = $helper->convertRatioToMinSize() ?>
	<div class="block product-list-block featured-list popular-product">
		<?php if($this->getTitle()!=''): ?>
			<div class="carousel_wrapper">
				<div class="block-title title">
					<h3><?php echo $this->getTitle() ?></h3>
				</div>
			</div>
		<?php endif ?>
		<div class="block-content">
			<ul class="products-list">
			<?php $i=0; foreach ($_products as $_product): ?>
				<?php $_product = Mage::getModel('catalog/product')->load($_product->getId()) ?>
				<li>
					<div class="border-top"></div>
					<div class="product-image">
						<a href="<?php echo $_product->getProductUrl() ?>">
						<img alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" class="img-responsive">
						 
						</a>
					</div>
					<div class="info-products">
						<div class="product-name"><a href="<?php echo $_product->getProductUrl() ?>">							
							 <?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?>
						 </a></div>
						 <?php echo $this->getPriceHtml($_product, true) ?>
						<?php //if ($_product->isSaleable()): ?>
								<!--button type="button" title="<?php //echo $this->__('Add to Cart') ?>" class="btn btn-primary btn-cart cart-product-grid btn-default" onclick="setLocation('<?php //echo $this->getAddToCartUrl($_product) ?>')"><?php //echo $this->__('Add to Cart') ?></button-->
							<?php //endif; ?>
					</div>
				</li>
			<?php endforeach ?>
			</ul>
		</div>
	</div>
<?php endif ?>