<?php if (Mage::getStoreConfig('deals/general/enabled')): ?>
    <?php
	$panelHelper = $this->helper('mpanel');
	$size = $panelHelper->convertRatioToSize();
	$_helper = $this->helper('catalog/output');	
    $layout = Mage::getSingleton('core/layout');
    $productCollection = $this->getProductCollection();
    $toolbar = $this->getToolbarBlock();
    $pager = $layout->createBlock('page/html_pager');
    $toolbar->setChild('product_list_toolbar_pager', $pager);
    $toolbar->setCollection($productCollection);
    
    $toolbar->setMode($this->getMode());
	$toolbar->setTemplate('mgs/deals/toolbar.phtml');
    echo $toolbar->toHtml();
	
	
    ?> 
    <?php if (count($productCollection) > 0): ?>
	<div class="category-products">
        <?php if ($this->getMode() != 'grid'): ?>
            <ul class="deals-container product-list">
                <?php foreach ($productCollection as $product): ?>
                    <?php $_product = Mage::getModel('catalog/product')->load($product->getId()) ?>
                    <li class="deal-item deal-list">						
							<div class="col-lg-3 col-md-3 col-sm-3">							
								<div class="border-img">
									<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
										<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive"/>
									</a>
									<div class="discount-save">
										<div class="save-content">
											
											<div class="percent">
												<?php $save = $_product->getPrice() - $_product->getFinalPrice() ?>
												<?php $percent = round(($save * 100) / $_product->getPrice(), 1) ?>
												<?php echo $percent ?>%
												<?php echo $this->__('OFF') ?>
											</div>
										</div>
									</div>
									
								</div>
                            
							</div>
							<div class="col-lg-9 col-md-9 col-sm-9">
							
									<div class="product-content">
										<div class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_product->getName(); ?></a></div> 
										<div class="product-description">
											<?php echo Mage::helper('core/string')->truncate($_product->getDescription(), 220); ?>
											<p class="view-detail"><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View details') ?></a></p>
										</div>										
										<div class="product-price-container">
											<?php echo $this->getPriceHtml($_product, true) ?>
										</div>
										<?php echo $this->getLayout()->createBlock('deals/deals')->setTemplate('mgs/deals/list.phtml')->setProductId($_product->getId())->toHtml(); ?>
									</div>
								
									<div class="deals-info">                           
										<div class="item-info">
											<div class="sold">
												<?php echo $this->__('Sold:') ?> <span><?php echo $this->getSold($_product->getId()) ?></span>
											</div>
											<div class="item-left">
												<?php $itemLeft = $this->getItemLeft($_product->getId()); ?>
												<?php if ($itemLeft != ''): ?>
													<?php if ($itemLeft > 1): ?>
														<?php echo $this->__('Items left:') ?> <span><?php echo $itemLeft ?></span>
													<?php else: ?>
														<?php echo $this->__('Item left:') ?> <span><?php echo $itemLeft ?></span>
													<?php endif ?>
												<?php else: ?>
													<?php echo $this->__('Items left:') ?> <span><?php echo $this->__('Unlimited') ?></span>
												<?php endif ?>
											</div>
										</div>
										<form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form_<?php echo $_product->getId(); ?>">
											<input name="qty" type="text" class="input-text qty addcart-qty" id="addcartqty" maxlength="12" value="<?php echo $this->getMinimalQty($_product) ?>" />
											<button class="btn btn-primary btn-cart" style="margin-bottom: 15px" onclick="productAddToCartForm_<?php echo $_product->getId(); ?>.submit();"><span><?php echo $this->__('Buy Now') ?></span></button>
										</form>
										<script type="text/javascript">
												var productAddToCartForm_<?php echo $_product->getId(); ?> = new VarienForm('product_addtocart_form_<?php echo $_product->getId(); ?>');
												productAddToCartForm_<?php echo $_product->getId(); ?>.submit = function() {
													if (this.validator.validate()) {
														this.form.submit();
													}
												}.bind(productAddToCartForm_<?php echo $_product->getId(); ?>);
										</script>
									</div>
							
							</div>
					
                    </li>
                <?php endforeach ?>
            </ul>
        <?php else: ?>
            <?php $_collectionSize = $productCollection->count() ?>
            <?php $_columnCount = $this->getColumnCount();?>
			<?php $col = $panelHelper->getCol() ?>
			<ul class="deal-container deal-grid"> 
            <?php
            $i = 0;
            foreach ($productCollection as $product):
                $_product = Mage::getModel('catalog/product')->load($product->getId());
                ?>                 
                    <li class="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?> col-md-<?php echo $col ?> col-sm-6 col-xs-12">
					<div class="product-image-wrapper">
					<div class="discount-save">
						<div class="save-content">										
										<div class="percent">
										<?php echo $this->__('SAVE') ?>
											<?php $save = $_product->getPrice() - $_product->getFinalPrice() ?>
											<?php $percent = round(($save*100)/$_product->getPrice(), 1) ?>
											<?php echo $percent ?>%											
										</div>									
						</div>
					</div>
					<div class="product-content">
						<div class="product-image">
							<a href="<?php echo $_product->getProductUrl() ?>" title="" class="product-image" >
								<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive" />
						
							</a>
						</div>
						<div class="info-products">
							<div class="product-name">
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
								
							</div>
							<div class="product-bottom"></div>
							<?php echo $this->getPriceHtml($_product, true) ?>
							<div class="actions">
								<ul class="add-to-links">
									<?php if($_product->isSaleable()): ?>
									<li>
										<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-cart btn-primary" onclick="setLocation('<?php echo $this->helper('checkout/cart')->getAddUrl($_product) ?>')"><i class="fa fa-shopping-cart"></i></button>
									<?php else: ?>
										<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
									</li>
									<?php endif; ?>
									<?php if($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
										<li><button class="btn btn-quickview quick-view hidden-xs hidden-sm" onclick="quickView('<?php echo $_product->getProductUrl() ?>'); return false;" title="<?php echo $this->__('Quick View') ?>"><i class="fa fa-search"></i></button></li>
									<?php endif ?>
									<?php if($_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product) && !Mage::getStoreConfig('mpanel/catalog/compare_button')): ?>
										<li><a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to Compare') ?>"><i class="fa fa-retweet"></i></a></li>
									<?php endif; ?>
									<?php if ($this->helper('wishlist')->isAllow() && !Mage::getStoreConfig('mpanel/catalog/wishlist_button')) : ?>
										<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><i class="fa fa-heart"></i></a></li>
									<?php endif; ?>
								</ul>
							</div>
						</div>
					</div>
					<a href="<?php echo $_product->getProductUrl()?>" class="arrows">
						<i class="fa fa-arrows"></i>
					</a>
				</div>
                    </li>
            <?php endforeach ?>
			</ul>
            <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last']);</script>
        <?php endif; ?>
    <?php endif; ?>
	</div>
<?php endif; ?>