<?php if(Mage::getStoreConfig('deals/general/enabled')): ?>
<?php
    $_productCollection=$this->getProductCollection();
    $_helper = $this->helper('catalog/output');	
	$helper = $this->helper('mpanel');
	$size = $helper->convertRatioToSize();
	$widgetId = $this->getWidgetId();
?>

<?php if(count($_productCollection)>0): ?>
	<?php $_columnCount = $this->getColumn(); ?>
	<div class="row deal-container">
		<div class="col-md-12">
		<?php if($this->getTitle()!=''): ?>
		  <div class="carousel_wrapper">
		   <div class="title title-name">
			<h4><?php echo $this->getTitle() ?></h4>
		   </div>
		  </div>
		</div>
		 <?php endif ?>
		<?php foreach ($_productCollection as $product): ?>
			<?php $_product = Mage::getModel('catalog/product')->load($product->getId()) ?>
			<div class="item col-md-<?php echo $helper->convertColRow($_columnCount) ?><?php if($_columnCount!=12): ?> col-sm-6 <?php endif ?> col-xs-12">
				<div class="product-image-wrapper">
					<div class="discount-save">
						<div class="save-content">										
										<div class="percent">
										<?php echo $this->__('SAVE') ?>
											<?php $save = $_product->getPrice() - $_product->getFinalPrice() ?>
											<?php $percent = round(($save*100)/$_product->getPrice(), 1) ?>
											<?php echo $percent ?>%											
										</div>									
						</div>
					</div>
					<div class="product-content">
						<div class="product-image">
							<a href="<?php echo $_product->getProductUrl() ?>" title="" class="product-image" >
								<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive" />
						
							</a>
						</div>
						<div class="info-products">
							<div class="product-name">
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
								
							</div>
							<div class="product-bottom"></div>
							<?php echo $this->getPriceHtml($_product, true) ?>
							<div class="actions">
								<ul class="add-to-links">
									<?php if($_product->isSaleable()): ?>
									<li>
										<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-cart btn-primary" onclick="setLocation('<?php echo $this->helper('checkout/cart')->getAddUrl($_product) ?>')"><i class="fa fa-shopping-cart"></i></button>
									<?php else: ?>
										<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
									</li>
									<?php endif; ?>
									<?php if($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
										<li><button class="btn btn-quickview quick-view hidden-xs hidden-sm" onclick="quickView('<?php echo $_product->getProductUrl() ?>'); return false;" title="<?php echo $this->__('Quick View') ?>"><i class="fa fa-search"></i></button></li>
									<?php endif ?>
									<?php if($_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product) && !Mage::getStoreConfig('mpanel/catalog/compare_button')): ?>
										<li><a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to Compare') ?>"><i class="fa fa-retweet"></i></a></li>
									<?php endif; ?>
									<?php if ($this->helper('wishlist')->isAllow() && !Mage::getStoreConfig('mpanel/catalog/wishlist_button')) : ?>
										<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><i class="fa fa-heart"></i></a></li>
									<?php endif; ?>
								</ul>
							</div>
						</div>
					</div>
					<a href="<?php echo $_product->getProductUrl()?>" class="arrows">
						<i class="fa fa-arrows"></i>
					</a>
				</div>
					<!--div class="deal-block-content">
						<div class="box-deal">							
						<?php //echo $this->getLayout()->createBlock('deals/deals')->setTemplate('mgs/deals/list.phtml')->setProductId($_product->getId())->setData("widgetId",$widgetId)->toHtml(); ?>
						</div>
					</div-->
			</div>
		<?php endforeach ?>
	</div>
<?php endif ?>
<?php endif ?>