<?php $megaMenu = $this->getMegamenuItems(); ?>
<?php if(count($megaMenu)>0 || Mage::getStoreConfig('megamenu/general/home')==1):?>
<nav class="megamenu navbar-collapse bs-navbar-collapse navbar-right mainnav col-md-10" role="navigation" >
	<ul class="nav-menu">
		<?php if(Mage::getStoreConfig('megamenu/general/home')==1): ?>
			<li class="<?php if($this->getUrl('') == $this->getUrl('*/*/*', array('_current'=>true, '_use_rewrite'=>true))):?> active <?php endif ?> level0">
				<a class="level0" href="<?php echo $this->getBaseUrl() ?>">
					<?php echo Mage::getStoreConfig('megamenu/general/hometext') ?>
				</a>
			</li>
		<?php endif ?>
		
		<?php if(count($megaMenu)>0): ?>
			<?php $i=0; foreach($megaMenu as $item): $i++ ?>
				<li class="<?php echo $this->getClass($item) ?>">
					<?php echo $this->getMenuHtml($item) ?>
				</li>
			<?php endforeach ?>
		<?php endif ?>
	</ul>
</nav>
<?php endif ?>
