<?php 
	$helper = $this->helper('mpanel');
	$cms = $helper->getExistCmsStatic('NOT IN');
	
	$category = $this->getCategory();
	$settings = $this->helper('mpanel')->getThemeSettings();
?>
<div>
	<div class="col-md-12">
		<div class="form-horizontal row">
			<div class="form-group">
				<label class="col-sm-3 control-label" for="display_mode"><?php echo $this->__('Display Mode') ?></label>
				<div class="col-sm-5">
					<select id="display_mode" class="form-control" name="general[display_mode]">
						<option value="<?php echo Mage_Catalog_Model_Category::DM_PRODUCT ?>"<?php if(Mage_Catalog_Model_Category::DM_PRODUCT == $category->getDisplayMode()): ?> selected="selected"<?php endif ?>><?php echo Mage::helper('catalog')->__('Products only') ?></option>
						<option value="<?php echo Mage_Catalog_Model_Category::DM_PAGE ?>"<?php if(Mage_Catalog_Model_Category::DM_PAGE == $category->getDisplayMode()): ?> selected="selected"<?php endif ?>><?php echo Mage::helper('catalog')->__('Static block only') ?></option>
						<option value="<?php echo Mage_Catalog_Model_Category::DM_MIXED ?>"<?php if(Mage_Catalog_Model_Category::DM_MIXED == $category->getDisplayMode()): ?> selected="selected"<?php endif ?>><?php echo Mage::helper('catalog')->__('Static block and products') ?></option>
					</select>
				</div>
			</div>
			
			<div class="form-group">
				<label class="col-sm-3 control-label" for="landing_page"><?php echo $this->__('CMS Block') ?></label>
				<div class="col-sm-5">
					<select id="landing_page" class="form-control" name="general[landing_page]">
						<option value=""><?php echo Mage::helper('catalog')->__('Please select a static block ...') ?></option>
						<?php foreach($cms as $_cms): ?>
							<option value="<?php echo $_cms->getId() ?>" <?php if($_cms->getId() == $category->getLandingPage()): ?> selected="selected"<?php endif ?>><?php echo $_cms->getTitle() ?></option>
						<?php endforeach ?>
					</select>
				</div>
			</div>
			
			<div class="form-group">
				<label class="col-sm-3 control-label" for="is_anchor"><?php echo $this->__('Is Anchor') ?></label>
				<div class="col-sm-5">
					<select id="is_anchor" class="form-control" name="general[is_anchor]">
						<option value="1"<?php if($category->getIsAnchor() == 1): ?> selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
						<option value="0"<?php if($category->getIsAnchor() == 0): ?> selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
					</select>
				</div>
			</div>
		</div>
	</div>
	
	<div class="col-md-12">
		<button class="btn btn-primary" type="submit"><span><span><?php echo $this->__('Update') ?></span></span></button>
	</div>
</div>