<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/colorPicker.css') ?>">
<script src="<?php echo $this->getSkinUrl('js/yahoo.color.js') ?>"></script>
<script src="<?php echo $this->getSkinUrl('js/colorPicker.js') ?>"></script>
<?php $settings = $this->helper('mpanel')->getThemeSettings() ?>
<div id="builder-general" style="display:block">
    <div class="col-md-12">
        <div class="form-horizontal row">
            <div id="accordion" class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion1" href="#collapseOne"><?php echo $this->__('General') ?></a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse">
                        <div class="panel-body">
						
							<div class="form-group">
                                <label for="page_width" class="col-sm-5 control-label"><?php echo $this->__('Width') ?></label>
                                <div class="col-sm-5">
                                    <select name="mgs_theme[general][page_width]" class="form-control" id="page_width">
                                        <option value="width1024"><?php echo $this->__('1024px') ?></option>
                                        <option value="width1200"<?php if ($settings['page_width'] == 'width1200'): ?> selected="selected"<?php endif ?>><?php echo $this->__('1200px') ?></option>
                                        <option value="width1366"<?php if ($settings['page_width'] == 'width1366'): ?> selected="selected"<?php endif ?>><?php echo $this->__('1366px') ?></option>
                                        <option value="fullwidth"<?php if ($settings['page_width'] == 'fullwidth'): ?> selected="selected"<?php endif ?>><?php echo $this->__('Full width') ?></option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="layout" class="col-sm-5 control-label"><?php echo $this->__('Right to left layout') ?></label>
                                <div class="col-sm-5">
                                    <select name="mgs_theme[general][right_to_left]" class="form-control" id="right_to_left">
                                        <option value="0"><?php echo $this->__('No') ?></option>
                                        <option value="1"<?php if ($settings['right_to_left'] == '1'): ?> selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="layout" class="col-sm-5 control-label"><?php echo $this->__('Layout') ?></label>
                                <div class="col-sm-5">
                                    <select name="mgs_theme[general][layout]" class="form-control" id="layout">
                                        <option value="wide"><?php echo $this->__('Wide') ?></option>
                                        <option value="boxed"<?php if ($settings['layout'] == 'boxed'): ?> selected="selected"<?php endif ?>><?php echo $this->__('Boxed') ?></option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="layout_style" class="col-sm-5 control-label"><?php echo $this->__('Layout Style') ?></label>
                                <div class="col-sm-5">
                                    <select name="mgs_theme[general][layout_style]" class="form-control" id="layout_style">
                                        <option value="light"><?php echo $this->__('Light') ?></option>
                                        <option value="dark"<?php if ($settings['layout_style'] == 'dark'): ?> selected="selected"<?php endif ?>><?php echo $this->__('Dark') ?></option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="sticky_menu" class="col-sm-5 control-label"><?php echo $this->__('Sticky menu') ?></label>
                                <div class="col-sm-5">
                                    <select name="mgs_theme[general][sticky_menu]" class="form-control" id="sticky_menu">
                                        <option value="0"><?php echo $this->__('No') ?></option>
                                        <option value="1"<?php if ($settings['sticky_menu'] == '1'): ?> selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="back_to_top" class="col-sm-5 control-label"><?php echo $this->__('Display back to top icon') ?></label>
                                <div class="col-sm-5">
                                    <select name="mgs_theme[general][back_to_top]" class="form-control" id="back_to_top">
                                        <option value="1"><?php echo $this->__('Yes') ?></option>
                                        <option value="0"<?php if (!$settings['back_to_top']): ?> selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="preloader" class="col-sm-5 control-label"><?php echo $this->__('Active Preloader') ?></label>
                                <div class="col-sm-5">
                                    <select name="mgs_theme[general][preloader]" class="form-control" id="preloader">
                                        <option value="1"><?php echo $this->__('Yes') ?></option>
                                        <option value="0"<?php if (!$settings['preloader']): ?> selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
                                    </select>
                                </div>
                            </div>
							
							<div class="form-group">
                                <label for="custom_css" class="col-sm-5 control-label"><?php echo $this->__('Custom css') ?></label>
                                <div class="col-sm-5">
                                    <select name="mgs_theme[general][custom_css]" class="form-control" id="custom_css">
                                        <option value="1"><?php echo $this->__('Yes') ?></option>
                                        <option value="0"<?php if (!$settings['custom_css']): ?> selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="snippets" class="col-sm-5 control-label"><?php echo $this->__('Enable Google rich snippets') ?></label>
                                <div class="col-sm-5">
                                    <select name="mgs_theme[general][snippets]" class="form-control" id="snippets">
                                        <option value="1"><?php echo $this->__('Yes') ?></option>
                                        <option value="0"<?php if (!$settings['snippets']): ?> selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
                                    </select>
                                </div>
                            </div>
							
							
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo"><?php echo $this->__('Background') ?></a>
                        </h4>
                    </div>
                    <div id="collapseTwo" class="panel-collapse collapse">
                        <div class="panel-body">

                            <div class="row">
                                <div class="col-sm-10">
                                    <div class="form-group">
                                        <label for="bg_color" class="col-sm-6 control-label"><?php echo $this->__('Background color') ?></label>
                                        <div class="col-sm-6">
                                            <input type="text" class="form-control" id="bg_color" name="mgs_theme[background][bg_color]" value="<?php echo str_replace('#', '', $settings['bg_color']) ?>"/>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="bg_color" class="col-sm-6 control-label"><?php echo $this->__('Background image') ?></label>
                                        <div class="col-sm-6">
                                            <input type="file" name="groups[background][fields][bg_upload][value]" id="mgs_theme_background_bg_upload" />
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="bg_image" class="col-sm-6 control-label"><?php echo $this->__('Background pattern') ?></label>
                                        <div class="col-sm-6 image-input">
                                            <?php $pattern = $this->helper('mpanel')->getBackgroundPattern(); ?>
                                            <select name="mgs_theme[background][bg_image]" class="form-control" id="theme_color"<?php if ($settings['bg_upload'] == ''): ?> onchange="changeBackgroundPattern(this.value)"<?php endif ?>>
                                                <?php foreach ($pattern as $_pattern): ?>
                                                    <option value="<?php echo $_pattern['value'] ?>"<?php if ($settings['bg_image'] == $_pattern['value']): ?> selected="selected"<?php endif ?>><?php echo $_pattern['label'] ?></option>
                                                <?php endforeach ?>
                                            </select>


                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="bg_repeat" class="col-sm-6 control-label"><?php echo $this->__('Background repeat') ?></label>
                                        <div class="col-sm-6">
                                            <select name="mgs_theme[background][bg_repeat]" class="form-control" id="bg_repeat" onchange="changeBackgroundMain()">
                                                <option value="repeat"><?php echo $this->__('Repeat') ?></option>
                                                <option value="repeat-x"<?php if ($settings['bg_repeat'] == 'repeat-x'): ?> selected="selected"<?php endif ?>><?php echo $this->__('Repeat X') ?></option>
                                                <option value="repeat-y"<?php if ($settings['bg_repeat'] == 'repeat-y'): ?> selected="selected"<?php endif ?>><?php echo $this->__('Repeat Y') ?></option>
                                                <option value="no-repeat"<?php if ($settings['bg_repeat'] == 'no-repeat'): ?> selected="selected"<?php endif ?>><?php echo $this->__('No Repeat') ?></option>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="bg_position_x" class="col-sm-6 control-label"><?php echo $this->__('Background position (x)') ?></label>
                                        <div class="col-sm-6">
                                            <select name="mgs_theme[background][bg_position_x]" class="form-control" id="bg_position_x" onchange="changeBackgroundMain()">
                                                <option value="left"><?php echo $this->__('Left') ?></option>
                                                <option value="right"<?php if ($settings['bg_position_x'] == 'right'): ?> selected="selected"<?php endif ?>><?php echo $this->__('Right') ?></option>
                                                <option value="center"<?php if ($settings['bg_position_x'] == 'center'): ?> selected="selected"<?php endif ?>><?php echo $this->__('Center') ?></option>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="bg_position_y" class="col-sm-6 control-label"><?php echo $this->__('Background position (y)') ?></label>
                                        <div class="col-sm-6">
                                            <select name="mgs_theme[background][bg_position_y]" class="form-control" id="bg_position_y" onchange="changeBackgroundMain()">
                                                <option value="top"><?php echo $this->__('Top') ?></option>
                                                <option value="bottom"<?php if ($settings['bg_position_y'] == 'right'): ?> selected="selected"<?php endif ?>><?php echo $this->__('Bottom') ?></option>
                                                <option value="center"<?php if ($settings['bg_position_y'] == 'center'): ?> selected="selected"<?php endif ?>><?php echo $this->__('Center') ?></option>
                                            </select>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-sm-4">
                                    <?php if ($settings['bg_upload'] != ''): ?>
                                        <div class="bg-thumbnail-image" style="margin-top:45px">
                                            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'mpanel/background/' . $settings['bg_upload'] ?>" alt="" class="img-responsive"/>
                                            <div class="checkbox">
                                                <label>
                                                    <input type="checkbox" id="mgs_theme_background_bg_upload_delete" class="checkbox" value="1" name="groups[background][fields][bg_upload][value][delete]" style="min-height:unset; padding:0; margin-top:4px"> <?php echo $this->__('Delete Image') ?>
                                                </label>
                                            </div>
                                        </div>
                                        <input type="hidden" value="<?php echo $settings['bg_upload'] ?>" name="groups[background][fields][bg_upload][value][value]"/>
                                    <?php else: ?>
                                        <div class="partern-thumbnail-image" style="margin-top:75px">
                                            <?php if ($settings['bg_image'] != ''): ?>
                                                <img src="<?php echo $this->getSkinUrl('images/patterns/' . $settings['bg_image'] . '.png') ?>" alt="" class="img-responsive" id="pattern_temp"/>
                                            <?php else: ?>
                                                <img src="" alt="" class="img-responsive" id="pattern_temp" style="display:none"/>
                                            <?php endif ?>
                                        </div>

                                        <input type="hidden" value="" name="groups[background][fields][bg_upload][value][value]" />
                                    <?php endif ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion3" href="#collapseThree"><?php echo $this->__('Color') ?></a>
                        </h4>
                    </div>
                    <div id="collapseThree" class="panel-collapse collapse">
                        <div class="panel-body">
                            <div class="form-group">
                                <label for="theme_color" class="col-sm-4 control-label"><?php echo $this->__('Theme color') ?></label>
                                <div class="col-sm-5">
                                    <?php $color = $this->helper('mpanel')->getThemeColor(); ?>
                                    <select name="mgs_theme[color][theme_color]" class="form-control" id="theme_color">
                                        <?php foreach ($color as $_color): ?>
                                            <option value="<?php echo $_color['value'] ?>"<?php if ($settings['theme_color'] == $_color['value']): ?> selected="selected"<?php endif ?>><?php echo $_color['label'] ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion3" href="#collapseFour"><?php echo $this->__('Fonts') ?></a>
                        </h4>
                    </div>
                    <div id="collapseFour" class="panel-collapse collapse">
                        <div class="panel-body">
                            <div class="form-group">
                                <label for="font" class="col-sm-4 control-label"><?php echo $this->__('Default font') ?></label>
                                <div class="col-sm-4">
                                    <?php $fonts = $this->helper('mpanel')->getFonts(); ?>
                                    <select name="mgs_theme[fonts][font]" class="form-control" id="font" onchange="changeFont(this.id)">
                                        <?php foreach ($fonts as $font): ?>
                                            <option value="<?php echo $font['css-name'] ?>"<?php if ($settings['font'] == $font['css-name']): ?> selected="selected"<?php endif ?>><?php echo $font['font-name'] ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                                <div class="col-sm-4">
                                    <span id="mgs_theme_fonts_font_view">Lorem ipsum dolor sit amet</span>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="h1" class="col-sm-4 control-label"><?php echo $this->__('Heading 1') ?></label>
                                <div class="col-sm-4">
                                    <?php $fonts = $this->helper('mpanel')->getFonts(); ?>
                                    <select name="mgs_theme[fonts][h1]" class="form-control" id="h1" onchange="changeFont(this.id)">
                                        <?php foreach ($fonts as $font): ?>
                                            <option value="<?php echo $font['css-name'] ?>"<?php if ($settings['h1'] == $font['css-name']): ?> selected="selected"<?php endif ?>><?php echo $font['font-name'] ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                                <div class="col-sm-4">
                                    <h1 id="mgs_theme_fonts_h1_view">Heading 1</h1>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="h2" class="col-sm-4 control-label"><?php echo $this->__('Heading 2') ?></label>
                                <div class="col-sm-4">
                                    <select name="mgs_theme[fonts][h2]" class="form-control" id="h2" onchange="changeFont(this.id)">
                                        <?php foreach ($fonts as $font): ?>
                                            <option value="<?php echo $font['css-name'] ?>"<?php if ($settings['h2'] == $font['css-name']): ?> selected="selected"<?php endif ?>><?php echo $font['font-name'] ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                                <div class="col-sm-4">
                                    <h2 id="mgs_theme_fonts_h2_view">Heading 2</h2>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="h3" class="col-sm-4 control-label"><?php echo $this->__('Heading 3') ?></label>
                                <div class="col-sm-4">
                                    <select name="mgs_theme[fonts][h3]" class="form-control" id="h3" onchange="changeFont(this.id)">
                                        <?php foreach ($fonts as $font): ?>
                                            <option value="<?php echo $font['css-name'] ?>"<?php if ($settings['h3'] == $font['css-name']): ?> selected="selected"<?php endif ?>><?php echo $font['font-name'] ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                                <div class="col-sm-4">
                                    <h3 id="mgs_theme_fonts_h3_view">Heading 3</h3>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="h4" class="col-sm-4 control-label"><?php echo $this->__('Heading 4') ?></label>
                                <div class="col-sm-4">
                                    <select name="mgs_theme[fonts][h4]" class="form-control" id="h4" onchange="changeFont(this.id)">
                                        <?php foreach ($fonts as $font): ?>
                                            <option value="<?php echo $font['css-name'] ?>"<?php if ($settings['h4'] == $font['css-name']): ?> selected="selected"<?php endif ?>><?php echo $font['font-name'] ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                                <div class="col-sm-4">
                                    <h4 id="mgs_theme_fonts_h4_view">Heading 4</h4>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="h5" class="col-sm-4 control-label"><?php echo $this->__('Heading 5') ?></label>
                                <div class="col-sm-4">
                                    <select name="mgs_theme[fonts][h5]" class="form-control" id="h5" onchange="changeFont(this.id)">
                                        <?php foreach ($fonts as $font): ?>
                                            <option value="<?php echo $font['css-name'] ?>"<?php if ($settings['h5'] == $font['css-name']): ?> selected="selected"<?php endif ?>><?php echo $font['font-name'] ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                                <div class="col-sm-4">
                                    <h5 id="mgs_theme_fonts_h5_view">Heading 5</h5>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="h6" class="col-sm-4 control-label"><?php echo $this->__('Heading 6') ?></label>
                                <div class="col-sm-4">
                                    <select name="mgs_theme[fonts][h6]" class="form-control" id="h6" onchange="changeFont(this.id)">
                                        <?php foreach ($fonts as $font): ?>
                                            <option value="<?php echo $font['css-name'] ?>"<?php if ($settings['h6'] == $font['css-name']): ?> selected="selected"<?php endif ?>><?php echo $font['font-name'] ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                                <div class="col-sm-4">
                                    <h6 id="mgs_theme_fonts_h6_view">Heading 6</h6>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="price" class="col-sm-4 control-label"><?php echo $this->__('Price') ?></label>
                                <div class="col-sm-4">
                                    <select name="mgs_theme[fonts][price]" class="form-control" id="price" onchange="changeFont(this.id)">
                                        <?php foreach ($fonts as $font): ?>
                                            <option value="<?php echo $font['css-name'] ?>"<?php if ($settings['price'] == $font['css-name']): ?> selected="selected"<?php endif ?>><?php echo $font['font-name'] ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                                <div class="col-sm-4">
                                    <div class="price-box"><span class="price" id="mgs_theme_fonts_price_view">$234</span></div>
                                </div>
                            </div>
							
							<div class="form-group">
                                <label for="menu" class="col-sm-4 control-label"><?php echo $this->__('Menu') ?></label>
                                <div class="col-sm-4">
                                    <select name="mgs_theme[fonts][menu]" class="form-control" id="menu" onchange="changeFont(this.id)">
                                        <?php foreach ($fonts as $font): ?>
                                            <option value="<?php echo $font['css-name'] ?>"<?php if ($settings['menu'] == $font['css-name']): ?> selected="selected"<?php endif ?>><?php echo $font['font-name'] ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                                <div class="col-sm-4">
                                    <div id="mgs_theme_fonts_menu_view" style="font-size: 16px;">HOME</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion4" href="#collapseFive"><?php echo $this->__('Extensions') ?></a>
                        </h4>
                    </div>
                    <div id="collapseFive" class="panel-collapse collapse">
                        <div class="panel-body">
                            <div class="form-group">
                                <label for="megamenu" class="col-sm-5 control-label"><?php echo $this->__('Enable Megamenu') ?></label>
                                <div class="col-sm-5">
                                    <select name="extension[megamenu][enabled]" class="form-control" id="megamenu">
                                        <option value="1"><?php echo $this->__('Yes') ?></option>
                                        <option value="0"<?php if ($settings['megamenu'] == 0): ?> selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="ajaxcart" class="col-sm-5 control-label"><?php echo $this->__('Enable Ajax Add to Cart') ?></label>
                                <div class="col-sm-5">
                                    <select name="extension[ajaxcart][active]" class="form-control" id="ajaxcart">
                                        <option value="1"><?php echo $this->__('Yes') ?></option>
                                        <option value="0"<?php if ($settings['ajaxcart'] == 0): ?> selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="quickview" class="col-sm-5 control-label"><?php echo $this->__('Enable Quick View') ?></label>
                                <div class="col-sm-5">
                                    <select name="extension[quickview][active]" class="form-control" id="quickview">
                                        <option value="1"><?php echo $this->__('Yes') ?></option>
                                        <option value="0"<?php if ($settings['quickview'] == 0): ?> selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="deals" class="col-sm-5 control-label"><?php echo $this->__('Enable Daily Deals') ?></label>
                                <div class="col-sm-5">
                                    <select name="extension[deals][enabled]" class="form-control" id="deals">
                                        <option value="1"><?php echo $this->__('Yes') ?></option>
                                        <option value="0"<?php if ($settings['deals'] == 0): ?> selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="oscheckout" class="col-sm-5 control-label"><?php echo $this->__('Enable One Step Checkout') ?></label>
                                <div class="col-sm-5">
                                    <select name="extension[oscheckout][enabled]" class="form-control" id="oscheckout">
                                        <option value="1"><?php echo $this->__('Yes') ?></option>
                                        <option value="0"<?php if ($settings['oscheckout'] == 0): ?> selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion5" href="#collapseSix"><?php echo $this->__('Catalog') ?></a>
                        </h4>
                    </div>
                    <div id="collapseSix" class="panel-collapse collapse">
                        <div class="panel-body">
                            <?php
                            $layout = Mage::getSingleton('page/source_layout')->toOptionArray();
                            array_unshift($layout, array('value' => '', 'label' => Mage::helper('catalog')->__('No layout updates')));
                            ?>
                            <div class="form-group">
                                <label for="catalog_layout" class="col-sm-6 control-label"><?php echo $this->__('Default Layout for Category Page') ?></label>
                                <div class="col-sm-6">
                                    <select name="catalog_config[layout]" class="form-control" id="catalog_layout">
                                        <?php foreach ($layout as $_layout): ?>
                                            <option value="<?php echo $_layout['value'] ?>"<?php if ($settings['catalog_layout'] == $_layout['value']): ?> selected="selected"<?php endif ?>><?php echo $_layout['label'] ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="product_layout" class="col-sm-6 control-label"><?php echo $this->__('Default Layout for Product Page') ?></label>
                                <div class="col-sm-6">
                                    <select name="catalog_config[product_layout]" class="form-control" id="product_layout">
                                        <?php foreach ($layout as $_layout): ?>
                                            <option value="<?php echo $_layout['value'] ?>"<?php if ($settings['product_layout'] == $_layout['value']): ?> selected="selected"<?php endif ?>><?php echo $_layout['label'] ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                            </div>
							
							<div class="form-group">
                                <label for="product_per_row" class="col-sm-6 control-label"><?php echo $this->__('Number Of Product Per Row') ?></label>
                                <div class="col-sm-6">
                                    <select name="catalog_config[product_per_row]" class="form-control" id="product_per_row">
										<option value="2"<?php if ($settings['product_per_row'] == 2): ?> selected="selected"<?php endif ?>>2</option>
										<option value="3"<?php if ($settings['product_per_row'] == 3): ?> selected="selected"<?php endif ?>>3</option>
										<option value="4"<?php if ($settings['product_per_row'] == 4): ?> selected="selected"<?php endif ?>>4</option>
										<option value="5"<?php if ($settings['product_per_row'] == 5): ?> selected="selected"<?php endif ?>>5</option>
										<option value="6"<?php if ($settings['product_per_row'] == 6): ?> selected="selected"<?php endif ?>>6</option>
										<option value="7"<?php if ($settings['product_per_row'] == 7): ?> selected="selected"<?php endif ?>>7</option>
										<option value="8"<?php if ($settings['product_per_row'] == 8): ?> selected="selected"<?php endif ?>>8</option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="featured" class="col-sm-6 control-label"><?php echo $this->__('Featured Product Attribute') ?></label>
                                <div class="col-sm-6">
                                    <?php
                                    $arrAttribute = array(array('value' => '', 'label' => ''));
                                    $productAttrs = Mage::getResourceModel('catalog/product_attribute_collection')
                                            ->addFieldToFilter('backend_type', 'int')
                                            ->addFieldToFilter('frontend_input', 'boolean')
                                            ->addFieldToFilter('source_model', 'eav/entity_attribute_source_boolean');
                                    if (count($productAttrs) > 0) {
                                        foreach ($productAttrs as $productAttr) {
                                            $arrAttribute[] = array(
                                                'value' => $productAttr->getAttributeCode(),
                                                'label' => $productAttr->getFrontendLabel()
                                            );
                                        }
                                    }
                                    ?>
                                    <select name="catalog_config[featured]" class="form-control" id="featured">
                                        <?php foreach ($arrAttribute as $_attribute): ?>
                                            <option value="<?php echo $_attribute['value'] ?>"<?php if ($settings['catalog_featured'] == $_attribute['value']): ?> selected="selected"<?php endif ?>><?php echo $_attribute['label'] ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                            </div>


                            <div class="form-group">
                                <label for="hot" class="col-sm-6 control-label"><?php echo $this->__('Best Selling Product Attribute') ?></label>
                                <div class="col-sm-6">
                                    <?php
                                    $arrAttribute = array(array('value' => '', 'label' => ''));
                                    $productAttrs = Mage::getResourceModel('catalog/product_attribute_collection')
                                            ->addFieldToFilter('backend_type', 'int')
                                            ->addFieldToFilter('frontend_input', 'boolean')
                                            ->addFieldToFilter('source_model', 'eav/entity_attribute_source_boolean');
                                    if (count($productAttrs) > 0) {
                                        foreach ($productAttrs as $productAttr) {
                                            $arrAttribute[] = array(
                                                'value' => $productAttr->getAttributeCode(),
                                                'label' => $productAttr->getFrontendLabel()
                                            );
                                        }
                                    }
                                    ?>
                                    <select name="catalog_config[hot]" class="form-control" id="hot">
                                        <?php foreach ($arrAttribute as $_attribute): ?>
                                            <option value="<?php echo $_attribute['value'] ?>"<?php if ($settings['catalog_hot'] == $_attribute['value']): ?> selected="selected"<?php endif ?>><?php echo $_attribute['label'] ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="brands" class="col-sm-6 control-label"><?php echo $this->__('Brands Attribute') ?></label>
                                <div class="col-sm-6">
                                    <?php
                                    $arrAttribute = array(array('value' => '', 'label' => ''));
                                    $productAttrs = Mage::getResourceModel('catalog/product_attribute_collection')
                                            ->addFieldToFilter('backend_type', 'int')
                                            ->addFieldToFilter('frontend_input', 'select')
                                    //->addFieldToFilter('source_model', 'eav/entity_attribute_source_table')
                                    ;
                                    if (count($productAttrs) > 0) {
                                        foreach ($productAttrs as $productAttr) {
                                            $arrAttribute[] = array(
                                                'value' => $productAttr->getAttributeCode(),
                                                'label' => $productAttr->getFrontendLabel()
                                            );
                                        }
                                    }
                                    ?>
                                    <select name="catalog_config[brands]" class="form-control" id="brands">
                                        <?php foreach ($arrAttribute as $_attribute): ?>
                                            <option value="<?php echo $_attribute['value'] ?>"<?php if ($settings['catalog_brands'] == $_attribute['value']): ?> selected="selected"<?php endif ?>><?php echo $_attribute['label'] ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="picture_ratio" class="col-sm-6 control-label"><?php echo $this->__('Product Picture ratio') ?></label>
                                <div class="col-sm-6">
                                    <?php
                                    $ratio = array(
                                        array('value' => '1', 'label' => Mage::helper('mpanel')->__('1/1 Square')),
                                        array('value' => '2', 'label' => Mage::helper('mpanel')->__('1/2 Portrait')),
                                        array('value' => '3', 'label' => Mage::helper('mpanel')->__('2/3 Portrait')),
                                        array('value' => '4', 'label' => Mage::helper('mpanel')->__('3/4 Portrait')),
                                        array('value' => '5', 'label' => Mage::helper('mpanel')->__('2/1 Landscape')),
                                        array('value' => '6', 'label' => Mage::helper('mpanel')->__('3/2 Landscape')),
                                        array('value' => '7', 'label' => Mage::helper('mpanel')->__('4/3 Landscape'))
                                    );
                                    ?>
                                    <select name="catalog_config[picture_ratio]" class="form-control" id="picture_ratio">
                                        <?php foreach ($ratio as $_ratio): ?>
                                            <option value="<?php echo $_ratio['value'] ?>"<?php if ($settings['picture_ratio'] == $_ratio['value']): ?> selected="selected"<?php endif ?>><?php echo $_ratio['label'] ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="new_label" class="col-sm-6 control-label"><?php echo $this->__('New Label') ?></label>
                                <div class="col-sm-6">
                                    <input type="text" class="input-text" name="catalog_config[new_label]" id="new_label" value="<?php echo $settings['new_label'] ?>"/>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="sale_label" class="col-sm-6 control-label"><?php echo $this->__('Sale Label') ?></label>
                                <div class="col-sm-6">
                                    <input type="text" class="input-text" name="catalog_config[sale_label]" id="sale_label" value="<?php echo $settings['sale_label'] ?>"/>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="price_slider" class="col-sm-6 control-label"><?php echo $this->__('Active Price Slider') ?></label>
                                <div class="col-sm-6">
                                    <select name="catalog_config[price_slider]" class="form-control" id="price_slider">
                                        <option value="1"><?php echo $this->__('Yes') ?></option>
                                        <option value="0"<?php if ($settings['price_slider'] == 0): ?> selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="more_view" class="col-sm-6 control-label"><?php echo $this->__('Active Ajax Load More Products') ?></label>
                                <div class="col-sm-6">
                                    <select name="catalog_config[more_view]" class="form-control" id="more_view">
                                        <option value="1"><?php echo $this->__('Yes') ?></option>
                                        <option value="0"<?php if ($settings['more_view'] == 0): ?> selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="preload" class="col-sm-6 control-label"><?php echo $this->__('Active Products Load Animation') ?></label>
                                <div class="col-sm-6">
                                    <select name="catalog_config[preload]" class="form-control" id="preload">
                                        <option value="1"><?php echo $this->__('Yes') ?></option>
                                        <option value="0"<?php if ($settings['preload'] == 0): ?> selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
                                    </select>
                                </div>
                            </div>
							
							<div class="form-group">
                                <label for="wishlist_button" class="col-sm-6 control-label"><?php echo $this->__('Hide Add to Wishlist button') ?></label>
                                <div class="col-sm-6">
                                    <select name="catalog_config[wishlist_button]" class="form-control" id="wishlist_button">
                                        <option value="1"><?php echo $this->__('Yes') ?></option>
                                        <option value="0"<?php if ($settings['wishlist_button'] == 0): ?> selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
                                    </select>
                                </div>
                            </div>
							
							<div class="form-group">
                                <label for="compare_button" class="col-sm-6 control-label"><?php echo $this->__('Hide Add to Compare button') ?></label>
                                <div class="col-sm-6">
                                    <select name="catalog_config[compare_button]" class="form-control" id="compare_button">
                                        <option value="1"><?php echo $this->__('Yes') ?></option>
                                        <option value="0"<?php if ($settings['compare_button'] == 0): ?> selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <button class="btn btn-primary" type="submit"><span><span><?php echo $this->__('Update') ?></span></span></button>
        <span class="button-fixed"><button class="btn btn-primary deactive" type="button" onclick="javascript:if(confirm('<?php echo $this->__('Are you sure you would like to restore theme configuration ?\n(This action just apply to default store config!)') ?>')) { setLocation('<?php echo $this->getUrl('mpanel/index/restore') ?>'); }"><span><span><?php echo $this->__('Restore Configuration') ?></span></span></button></span>
    </div>
</div>

<script type="text/javascript">
    // <![CDATA[
    new Control.ColorPicker("bg_color", { IMAGE_BASE : "<?php echo $this->getSkinUrl('images') ?>/" });
    // ]]>

    mgsjQuery('#mgs_theme_background_bg_upload').change( function(event) {
        if($('wrapper')){
            var tmppath = URL.createObjectURL(event.target.files[0]);
            mgsjQuery("body").css('background-image','url('+tmppath+')');
            changeBackgroundMain();
        }
    });
	
    function changeBackgroundMain(){
        bgPosition = mgsjQuery('#bg_position_x').val() + " " + mgsjQuery('#bg_position_y').val();
        mgsjQuery("body").css('background-repeat',mgsjQuery('#bg_repeat').val());
        mgsjQuery("body").css('background-position',bgPosition);
    }
	
    function changeBackgroundPattern(pattern){
        if(pattern!=''){
            mgsjQuery('#pattern_temp').attr('src','<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) ?>frontend/mgstheme/default/images/patterns/'+pattern+'.png');
            mgsjQuery('#pattern_temp').show();
            if($('wrapper')){
                mgsjQuery("body").css('background-image','url(<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) ?>frontend/mgstheme/default/images/patterns/'+pattern+'.png)');
                changeBackgroundMain();
            }
        }
        else{
            mgsjQuery('#pattern_temp').hide();
            if($('wrapper')){
                mgsjQuery("body").css('background-image','none');
            }
        }
    }
</script>