<?php if (($_products = $this->getSpecialProducts('hot')) && (count($_products)>0)): ?>
	<?php $helper = $this->helper('mpanel') ?>
	<?php $size = $helper->convertRatioToSize() ?>
		<?php if($this->getRequest()->getParam('perrow')): ?>
			<?php $perrow = $this->getRequest()->getParam('perrow') ?>
		<?php else: ?>
			<?php $perrow = $this->getCountPerRow() ?>
		<?php endif ?>
		
		<?php $i=0; foreach ($_products as $_product): ?>
			<?php $_product = Mage::getModel('catalog/product')->load($_product->getId()) ?>
			<li class="item col-md-<?php echo $helper->convertColRow($perrow) ?> col-sm-6 col-xs-12">
				<div class="product-image-wrapper">
							
							<?php echo $helper->getProductLabel($_product) ?>
							
							<div class="product-content">
								<div class="product-image">
									<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
										<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive"/>
									
									</a>
								</div>
								<div class="info-products">
									<div class="product-name">
										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a>
										
									</div>
									<div class="product-bottom"></div>
									<?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
									<div class="actions">										
											<ul class="add-to-links">
												<?php if ($_product->isSaleable()): ?>
												<li>
													<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-cart cart-product-grid btn-default btn-primary" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><i class="fa fa-shopping-cart"></i></button>
												</li>
												<?php endif; ?>	
												<?php if($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
												<li><button class="btn btn-quickview quick-view hidden-xs hidden-sm" onclick="quickView('<?php echo $_product->getProductUrl() ?>'); return false;" title="<?php echo $this->__('Quick View') ?>"><i class="fa fa-search"></i></button></li>
												<?php endif ?>										
												<?php if($_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product) && !Mage::getStoreConfig('mpanel/catalog/compare_button')): ?>
													<li><a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to Compare') ?>"><i class="fa fa-retweet"></i></a></li>
												<?php endif; ?>
												<?php if ($this->helper('wishlist')->isAllow() && !Mage::getStoreConfig('mpanel/catalog/wishlist_button')) : ?>
													<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><i class="fa fa-heart"></i></a></li>
												<?php endif; ?>
											</ul>									
									</div>
								</div>
							</div>
							<a class="arrows" href="<?php echo $_product->getProductUrl() ?>">
								<i class="fa fa-arrows"></i>
							</a>
						</div>
			</li>
		<?php endforeach ?>
<?php endif ?>