<?php $helper = $this->helper('mpanel') ?>
<div class="home-1column-full">
	<?php // Block 1 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 1, 'builder-container section1') ?>>
			<div class="container">
				<?php echo $helper->getEditPanel('1_column_full', 1) ?>
				<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block1')->setTemplate('mgs/mpanel/template/admin/child.phtml')->toHtml() ?>
			</div>
	</section>

	<?php // Block 2 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 2, 'builder-container section1') ?>>
		<div class="container">
			<?php echo $helper->getEditPanel('1_column_full', 2) ?>
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block2')->setTemplate('mgs/mpanel/template/admin/child.phtml')->toHtml() ?>
		</div>
	</section>

	<?php // Block 3 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 3, 'builder-container section1') ?>>
		<div class="container">
			<?php echo $helper->getEditPanel('1_column_full', 3) ?>
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block3')->setTemplate('mgs/mpanel/template/admin/child.phtml')->toHtml() ?>
		</div>
	</section>

	<?php // Block 4 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 4, 'builder-container section1') ?>>
		<div class="container">
			<?php echo $helper->getEditPanel('1_column_full', 4) ?>
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block4')->setTemplate('mgs/mpanel/template/admin/child.phtml')->toHtml() ?>
		</div>
	</section>
	
	<?php // Block 5 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 5, 'builder-container section1') ?>>
		<div class="container">
			<?php echo $helper->getEditPanel('1_column_full', 5) ?>
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block5')->setTemplate('mgs/mpanel/template/admin/child.phtml')->toHtml() ?>
		</div>
	</section>
	
	<?php // Block 6 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 6, 'builder-container section1') ?>>
		<div class="container">
			<?php echo $helper->getEditPanel('1_column_full', 6) ?>
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block6')->setTemplate('mgs/mpanel/template/admin/child.phtml')->toHtml() ?>
		</div>
	</section>
	
	<?php // Block 7 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 7, 'builder-container section1') ?>>
		<div class="container">
			<?php echo $helper->getEditPanel('1_column_full', 7) ?>
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block7')->setTemplate('mgs/mpanel/template/admin/child.phtml')->toHtml() ?>
		</div>
	</section>
	
	<?php // Block 8 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 8, 'builder-container section1') ?>>
		<div class="container">
			<?php echo $helper->getEditPanel('1_column_full', 8) ?>
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block8')->setTemplate('mgs/mpanel/template/admin/child.phtml')->toHtml() ?>
		</div>
	</section>
	
	<?php // Block 9 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 9, 'builder-container section1') ?>>
		<div class="container">
			<?php echo $helper->getEditPanel('1_column_full', 9) ?>
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block9')->setTemplate('mgs/mpanel/template/admin/child.phtml')->toHtml() ?>
		</div>
	</section>
	
	<?php // Block 10 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 10, 'builder-container section1') ?>>
		<div class="container">
			<?php echo $helper->getEditPanel('1_column_full', 10) ?>
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block10')->setTemplate('mgs/mpanel/template/admin/child.phtml')->toHtml() ?>
		</div>
	</section>
	
	<?php // Block 11 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 11, 'builder-container section1') ?>>
		<div class="container">
			<?php echo $helper->getEditPanel('1_column_full', 11) ?>
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block11')->setTemplate('mgs/mpanel/template/admin/child.phtml')->toHtml() ?>
		</div>
	</section>
	
	<?php // Block 12 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 12, 'builder-container section1') ?>>
		<div class="container">
			<?php echo $helper->getEditPanel('1_column_full', 12) ?>
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block12')->setTemplate('mgs/mpanel/template/admin/child.phtml')->toHtml() ?>
		</div>
	</section>
	
	<?php // Block 13 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 13, 'builder-container section1') ?>>
		<div class="container">
			<?php echo $helper->getEditPanel('1_column_full', 13) ?>
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block13')->setTemplate('mgs/mpanel/template/admin/child.phtml')->toHtml() ?>
		</div>
	</section>
	
	<?php // Block 14 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 14, 'builder-container section1') ?>>
		<div class="container">
			<?php echo $helper->getEditPanel('1_column_full', 14) ?>
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block14')->setTemplate('mgs/mpanel/template/admin/child.phtml')->toHtml() ?>
		</div>
	</section>
	
	<?php // Block 15 content ?>
	<section<?php echo $this->getBlockSetting('1_column_full', 15, 'builder-container section1') ?>>
		<div class="container">
			<?php echo $helper->getEditPanel('1_column_full', 15) ?>
			<?php echo $this->getLayout()->createBlock('mpanel/template_child')->setTemplateLayout('1_column_full')->setBlockName('block15')->setTemplate('mgs/mpanel/template/admin/child.phtml')->toHtml() ?>
		</div>
	</section>
</div>