<?php
/**
 * Customer confirm form template
 *
 * @see Qbikz_InformaxionSms_Block_Customer_Form_Confirm_Login
 * @var $this Qbikz_InformaxionSms_Block_Customer_Form_Confirm_Login
 */
 ?>
<div class="account-login imsms_confirm_code">
    <div class="page-title">
        <h1><?php echo $this->__('Confirm an Account') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php /* Extensions placeholder */ ?>
    <?php echo $this->getChildHtml('customer.form.login.extra')?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="col-main">
            <div class="registered-users">
                <div class="content">
                    <p><?php echo $this->__('Our service sent you OTP to confirm your account. Please enter OTP.') ?></p>
                    <ul class="form-list">
                        <li>
                            <label for="smscode" class="required"><em>*</em><?php echo $this->__('SMS Code') ?></label>
                            <div class="input-box">
                                <input autocomplete="off" type="text" name="smscode" value="<?php echo $this->escapeHtml($this->getSms()) ?>" id="smscode" class="input-text required-entry" title="<?php echo $this->escapeHtml($this->__('SMS Code')) ?>" />
                            </div>
                        </li>
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                    </ul>
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                </div>
            </div>
        </div>
        <div class="col-main">
            <div class="registered-users">
                <div class="buttons-set">
                    <button type="submit" class="otp-btn btn btn-primary btn-default" title="<?php echo $this->__('Verify') ?>" name="sendbtn" id="sendbtn"><em class="fa-icon"><i class="fa fa-check" style="padding-right:10px;"></i></em><span><span><?php echo $this->__('Verify') ?></span></span></button>
                </div>
            </div>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
</div>
