<?php
/**
 * Customer confirm form template
 *
 * @see Qbikz_InformaxionSms_Block_Customer_Form_Confirm_Resetpassword
 * @var $this Qbikz_InformaxionSms_Block_Customer_Form_Confirm_Resetpassword
 */
?>
<div class="account-login imsms_confirm_code">
    <div class="page-title">
        <h1><?php echo $this->__('Confirm an Reset Password') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="resetpassword-form">
        <div class="col-main">
            <div class="registered-users">
                <div class="content">
                    <h2><?php echo $this->__('Confirm SMS Code / Reset Password') ?></h2>
                    <p><?php echo $this->__('Our service sent you SMS message to confirm your account. Please enter SMS code.') ?></p>
                    <ul class="form-list">
                        <li>
                            <label for="smscode" class="required"><em>*</em><?php echo $this->__('SMS Code') ?></label>
                            <div class="input-box">
                                <input autocomplete="off" type="text" name="smscode" value="<?php echo $this->escapeHtml($this->getSmsRPCode()) ?>" id="smscode" class="input-text required-entry" title="<?php echo $this->escapeHtml($this->__('SMS Code')) ?>" />
                            </div>
                        </li>
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                    </ul>
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                </div>
            </div>
        </div>
        <div class="col-main">
            <div class="registered-users">
                <div class="buttons-set">
                    <button type="submit" class="button" title="<?php echo $this->__('Confirm') ?>" name="sendbtn" id="sendbtn"><span><span><?php echo $this->__('Confirm') ?></span></span></button>
                </div>
            </div>
        </div>
    </form>
    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('resetpassword-form', true);
        //]]>
    </script>
</div>