<?php if (($_products = $this->getSpecialProducts('featured')) && (count($_products)>0)): ?>
	<?php $helper = $this->helper('mpanel') ?>
	<?php $size = $helper->convertRatioToMinSize() ?>
	<div class="block product-list-block featured-list">
		<?php if($this->getTitle()!=''): ?>
			<div class="block-title">
				<h2><?php echo $this->getTitle() ?></h2>
			</div>
		<?php endif ?>
		<div class="block-content">
			<ul class="products-list">
			<?php $i=0; foreach ($_products as $_product): ?>
				<?php $_product = Mage::getModel('catalog/product')->load($_product->getId()) ?>
				<li class="item">
				
					<a href="<?php echo $_product->getProductUrl() ?>">
						<img alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" class="img-responsive img-thumbnail">
						 <?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?>
					 </a>
				
					<?php echo $this->getPriceHtml($_product, true) ?>
					
					<?php if ($_product->isSaleable()): ?>
						<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-primary btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><em class="fa fa-shopping-cart"></em><?php echo $this->__('Add to Cart') ?></button>
					<?php endif; ?>
				</li>
			<?php endforeach ?>
			</ul>
		</div>
	</div>
<?php endif ?>