<?php 
	$categories = $this->getCategoryCollection();
	$panelHelper = $this->helper('mpanel');
	$size = $panelHelper->convertRatioToSize();
	if($this->getColumn()){
		$col = $this->getColumn();
	}
	else{
		$col = 3;
	}
	
	$col = $panelHelper->convertColRow($col);
?>
<?php if($this->getTitle()!=''): ?>
	<div class="carousel_wrapper carousel-title">
		<div class="title title-name ">
			<h4><?php echo $this->getTitle() ?></h4>
		</div>
	</div>
<?php endif ?>

<?php if(count($categories)>0): ?>
	<div class="featured-category-products category-products-simple">
		
			<?php foreach($categories as $_category): ?>
				<div class="carousel-container">
					<div class="category-product-item col-md-12">
						<?php $products = $this->getProductByCategory($_category) ?>
						<?php $_collectionSize = count($products) ?>
						<?php $_columnCount = 2*$this->getColumn(); ?>
						<?php if(count($products)>0): ?>
							<div class="products-grid<?php if($col == 'custom-5' || $col == 'custom-7' || $col == 'custom-8'): ?> col-md-<?php echo $col; ?><?php endif; ?> products-carousel" id="grid-slider-category-product-<?php echo $_category->getId() ?>">
								<?php $i=0; foreach($products as $_product): ?>
									<?php if ($i++%$_columnCount==0): ?>
										<div class="item">
									<?php endif ?>
									<?php //$_product = Mage::getModel('catalog/product')->load($_product) ?>
									<div class="<?php if($col !=''): ?>col-md-<?php echo $col; ?> col-sm-6 col-xs-12<?php endif; ?>">
										<div class="product-image-wrapper">
											<?php echo $panelHelper->getProductLabel($_product) ?>
											<div class="product-content">
												<div class="product-image">
													<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
														<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive"/>
														
													</a>
												</div>
												<div class="info-products">
													<div class="product-name">
														<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a>
														
													</div>
													<div class="product-bottom"></div>
													<?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
													<div class="actions">
															<ul class="add-to-links tooltip-links">
																<?php if ($_product->isSaleable()): ?>
																<li>
																<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-primary btn-cart cart-product-grid" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><i class="fa fa-shopping-cart"></i></button>
																</li>
																<?php endif; ?>
																<?php if($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
																<li>
																<button class="btn btn-quickview quick-view hidden-xs hidden-sm" onclick="quickView('<?php echo $_product->getProductUrl() ?>'); return false;" title="<?php echo $this->__('Quick View') ?>"><i class="fa fa-search"></i></button>
																</li>
																<?php endif ?>
																<?php if ($this->helper('wishlist')->isAllow() && !Mage::getStoreConfig('mpanel/catalog/wishlist_button')) : ?>
																	<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist btn" title="<?php echo $this->__('Add to Wishlist') ?>"><i class="fa fa-heart"></i></a></li>
																<?php endif; ?>
																<?php if($_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product) && !Mage::getStoreConfig('mpanel/catalog/compare_button')): ?>
																	<li><a href="<?php echo $_compareUrl ?>" class="link-compare btn" title="<?php echo $this->__('Add to Compare') ?>"><i class="fa fa-retweet"></i></a></li>
																<?php endif; ?>
															</ul>
														
													</div>
												</div>
												
											</div>
											<a href="<?php echo $_product->getProductUrl() ?>" class="arrows"><i class="fa fa-arrows"></i></a>
										</div>
									</div>
									<?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
										</div>
									<?php endif ?>
								<?php endforeach ?>
							</div>
						<?php endif ?>
					</div>
				</div>
				
				<script type="text/javascript">
					initSlider('grid-slider-category-product-<?php echo $_category->getId() ?>', 1, false, false, true, false);
				</script>
				
				<?php endforeach ?>
		
	</div>
<?php endif ?>