<?php 
	$categories = $this->getCategoryCollection();
	$panelHelper = $this->helper('mpanel');
	$size = $panelHelper->convertRatioToMinSize();
	if($this->getColumn()){
		$col = $this->getColumn();
	}
	else{
		$col = 3;
	}
	
	$col = $panelHelper->convertColRow($col);
?>


<?php if(count($categories)>0): ?>
	<div class="block product-list-block category-product-list popular-product">
		<?php if($this->getTitle()!=''): ?>
			<div class="carousel_wrapper">
				<div class="title title-name ">
					<h4><?php echo $this->getTitle() ?></h4>
				</div>
			</div>
		<?php endif ?>
		<div class="product-list">
			<?php foreach($categories as $_category): ?>
				<div class="products-list">
					<?php $products = $this->getProductByCategory($_category) ?>
					<?php if(count($products)>0): ?>
						<?php $i=0; foreach ($products as $_product): ?>
							<div class="item">
								<div class="product-image">
									<a href="<?php echo $_product->getProductUrl() ?>">
									<img alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" class="img-responsive">
									 
									</a>
								</div>
								<div class="info-products">
									<div class="product-name"><a href="<?php echo $_product->getProductUrl() ?>">							
										 <?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?>
									 </a></div>
									 <?php echo $this->getPriceHtml($_product, true) ?>
								</div>
							</div>
						<?php endforeach ?>
					<?php endif ?>
				</div>
			<?php endforeach ?>
		</div>

	</div>
<?php endif ?>