<?php $template = $this->getRequest()->getParam('template') ?>
<?php $block = $this->getRequest()->getParam('block') ?>

<?php 
	$exist = 0;
	if($id = $this->getRequest()->getParam('id')){
		$child =  Mage::getModel('mpanel/childs')->load($id);
		$exist = 1;
		$settings = json_decode($child->getSetting(), true);
	}
?>
<?php $helper = $this->helper('mpanel') ?>
<?php if($helper->acceptToUsePanel()): ?>
	
		<div class="edit-static-form">
		
			
			<form id="edit_form" method="post" action="<?php echo $this->getUrl('mpanel/post/child') ?>">
			
				<div class="row">
					<div class="col-md-12 builder-title">
						<h2><?php echo $this->__('Best Selling Products Block') ?></h2>
					</div>
				</div>
				
				<div class="form-horizontal">
					<div class="row">
						<div class="form-group">
							<label class="col-sm-4 control-label" for="col"><?php echo $this->__('Block col (12 to full)') ?></label>
							<div class="col-sm-8">
								<select name="col" class="required-entry input-text" id="col">
									<?php for($i=12; $i>=1; $i--): ?>
										<option value="<?php echo $i ?>"<?php if($exist && ($child->getCol()==$i)): ?> selected="selected"<?php endif ?>><?php echo $i ?></option>
									<?php endfor ?>
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<label class="col-sm-4 control-label" for="custom_class"><?php echo $this->__('Custom Class') ?></label>
							<div class="col-sm-8">
								<input type="text" name="setting[custom_class]" class="input-text" id="custom_class"<?php if($exist): ?> value="<?php echo $settings['custom_class'] ?>"<?php endif ?> />
							</div>
						</div>
						
						<div class="form-group">
							<label class="col-sm-4 control-label" for="animation"><?php echo $this->__('Block Animation') ?></label>
							<div class="col-sm-4">
								<select name="setting[animation]" class="input-text" id="animation" onchange="changeAnimationClass(this.value)">
									<?php $animation = $helper->getAnimationClass() ?>
									<?php foreach($animation as $_animate): ?>
										<option value="<?php echo $_animate['value'] ?>"<?php if($exist && ($settings['animation']==$_animate['value'])): ?> selected="selected"<?php endif ?>><?php echo $_animate['label'] ?></option>
									<?php endforeach ?>
								</select>
							</div>
							<div class="col-sm-4 text-center animated<?php if($exist && ($settings['animation']!='')): ?> <?php echo $settings['animation'] ?><?php endif ?>" id="animation-test"><h1>Animation Preview</h1></div>
						</div>
						
						<div class="form-group">
							<label class="col-sm-4 control-label" for="animation_delay"><?php echo $this->__('Animation Delay') ?></label>
							<div class="col-sm-8">
								<input type="text" name="setting[animation_delay]" class="input-text validate-number" id="animation_delay" placeholder="ms" <?php if($exist && isset($settings['animation_delay'])): ?> value="<?php echo $settings['animation_delay'] ?>"<?php endif ?>/>
							</div>
						</div>
						
						<div class="form-group">
							<input type="hidden" value="hot" name="type" id="block_type"/>
							<input type="hidden" value="<?php echo $template ?>" name="home_name" id="block_home_name"/>
							<input type="hidden" value="<?php echo $block ?>" name="block_name" id="block_block_name"/>
							<?php if($exist): ?>
								<input type="hidden" value="<?php echo $child->getId() ?>" name="child_id" />
							<?php endif ?>
							
							<label class="col-sm-4 control-label" for="product_count"><?php echo $this->__('Number of Products') ?></label>
							<div class="col-sm-8">
								<input type="text" name="setting[product_count]" class="required-entry input-text validate-number validate-greater-than-zero" id="product_count"<?php if($exist): ?> value="<?php echo $settings['product_count'] ?>"<?php endif ?>/>
							</div>
						</div>
						
						<div class="form-group">
							<label class="col-sm-4 control-label" for="title"><?php echo $this->__('Title') ?></label>
							<div class="col-sm-8">
								<input type="text" name="setting[title]" class="input-text" id="title"<?php if($exist): ?> value="<?php echo $settings['title'] ?>"<?php endif ?>/>
							</div>
						</div>
						
						<div class="form-group">
							<label class="col-sm-4 control-label" for="view_mode"><?php echo $this->__('View mode') ?></label>
							<div class="col-sm-8">
								<select name="setting[view_mode]" class="required-entry input-text" id="view_mode" onchange="toggleViewmode(this.value)">
									<option value="grid"<?php if($exist && ($settings['view_mode']=='grid')): ?> selected="selected"<?php endif ?>><?php echo $this->__('Grid') ?></option>
									<option value="list"<?php if($exist && ($settings['view_mode']=='list')): ?> selected="selected"<?php endif ?>><?php echo $this->__('List') ?></option>
								</select>
							</div>
						</div>
						
						<div class="form-group viewmode-setting">
							<label class="col-sm-4 control-label" for="count_per_row"><?php echo $this->__('Number of Products per row') ?></label>
							<div class="col-sm-8">
								<select name="setting[count_per_row]" class="required-entry input-text" id="count_per_row">
									<option value="1"<?php if($exist && ($settings['count_per_row']==1)): ?> selected="selected"<?php endif ?>>1</option>
									<option value="2"<?php if($exist && ($settings['count_per_row']==2)): ?> selected="selected"<?php endif ?>>2</option>
									<option value="3"<?php if($exist && ($settings['count_per_row']==3)): ?> selected="selected"<?php endif ?>>3</option>
									<option value="4"<?php if($exist && ($settings['count_per_row']==4)): ?> selected="selected"<?php endif ?>>4</option>
									<option value="6"<?php if($exist && ($settings['count_per_row']==6)): ?> selected="selected"<?php endif ?>>6</option>
								</select>
							</div>
						</div>
						
						
						
						<div class="form-group viewmode-setting">
							<label class="col-sm-4 control-label" for="slider"><?php echo $this->__('Use slider') ?></label>
							<div class="col-sm-8">
								<select name="setting[slider][active]" class="required-entry input-text" id="slider" onchange="toggleSliderSettings(this.value)">
									<option value="0"<?php if($exist && ($settings['slider']['active']==0)): ?> selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
									<option value="1"<?php if($exist && ($settings['slider']['active']==1)): ?> selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
								</select>
							</div>
						</div>
					</div>
					
					<div class="row" id="loadmore-setting"<?php if(($exist && ($settings['slider']['active']==1))): ?> style="display:none"<?php endif ?>>
						<hr/>
						
						<div class="form-group">
							<label class="col-sm-4 control-label" for="load_more"><?php echo $this->__('Visible load more button') ?></label>
							<div class="col-sm-8">
								<select name="setting[load_more]" class="required-entry input-text" id="load_more">
									<option value="0"><?php echo $this->__('No') ?></option>
									<option value="1"<?php if($exist && ($settings['load_more']==1)): ?> selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
								</select>
							</div>
						</div>
					</div>
					
					<div class="row slider-config" id="slider-settings"<?php if(($exist && ($settings['slider']['active']==0)) || !$exist): ?> style="display:none"<?php endif ?>>
						<hr/>
						<div class="form-group">
							<label class="col-sm-4 control-label" for="auto_play"><?php echo $this->__('Auto play') ?></label>
							<div class="col-sm-8">
								<select name="setting[slider][auto]" class="required-entry input-text" id="auto_play">
									<option value="false"<?php if($exist && ($settings['slider']['auto']=='false')): ?> selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
									<option value="true"<?php if($exist && ($settings['slider']['auto']=='true')): ?> selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<label class="col-sm-4 control-label" for="stop_hover"><?php echo $this->__('Stop autoplay on mouse hover') ?></label>
							<div class="col-sm-8">
								<select name="setting[slider][stop_hover]" class="required-entry input-text" id="stop_hover">
									<option value="false"<?php if($exist && ($settings['slider']['stop_hover']=='false')): ?> selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
									<option value="true"<?php if($exist && ($settings['slider']['stop_hover']=='true')): ?> selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<label class="col-sm-4 control-label" for="navigation"><?php echo $this->__('Display Navigation') ?></label>
							<div class="col-sm-8">
								<select name="setting[slider][navigation]" class="required-entry input-text" id="navigation">
									<option value="false"<?php if($exist && ($settings['slider']['navigation']=='false')): ?> selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
									<option value="true"<?php if($exist && ($settings['slider']['navigation']=='true')): ?> selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<label class="col-sm-4 control-label" for="pagination"><?php echo $this->__('Display Pagination') ?></label>
							<div class="col-sm-8">
								<select name="setting[slider][pagination]" class="required-entry input-text" id="pagination">
									<option value="false"<?php if($exist && ($settings['slider']['pagination']=='false')): ?> selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
									<option value="true"<?php if($exist && ($settings['slider']['pagination']=='true')): ?> selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
								</select>
							</div>
						</div>
					</div>
					
					<div class="row builder-action">
						<div class="col-md-12">
							<div class="buttons">
								<?php if(!$exist): ?>
									<button onclick="history.go(-1)" class="btn btn-back" type="button">
										<span><span><?php echo $this->__('Back') ?></span></span>
									</button>
								<?php endif ?>
								<button id="submit-button" onclick="updateForm.submit(this)" class="btn btn-primary" type="button">
									<span><span><?php echo $this->__('Submit') ?></span></span>
								</button>
							</div>
						</div>
					</div>
				</div>
			</form>
		</div>
	<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('mgs/mpanel/form/script_action.phtml')->toHtml() ?>
	<script type="text/javascript">
		function toggleSliderSettings(val){
			if(val==1){
				$('slider-settings').show();
			}
			else{
				$('slider-settings').hide();
			}
			
			mgsjQuery('#loadmore-setting').toggle();
		}
		
		function toggleViewmode(val){
			if(val=='grid'){
				mgsjQuery('.viewmode-setting').show();
				$('loadmore-setting').show();
			}
			else{
				mgsjQuery('.viewmode-setting').hide();
				$('loadmore-setting').hide();
			}
		}
		<?php if($exist): ?>
			toggleViewmode('<?php echo $settings['view_mode'] ?>');
		<?php endif ?>
		
		var currentAnimate = '';
		<?php if($exist): ?>
			currentAnimate = '<?php echo $settings['animation'] ?>';
		<?php endif ?>
		
		function changeAnimationClass(animate){
			if(currentAnimate!=''){
				mgsjQuery('#animation-test').removeClass(currentAnimate);
			}
			mgsjQuery('#animation-test').addClass(animate);
			currentAnimate = animate;
		}
	</script>
<?php endif ?>