<?php $post = $this->getPost(); ?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="postWrapper wrapper">
    <div class="postTitle">
        <h3><?php echo $post->getTitle(); ?></h3>
    </div>
	<div class="postDetails">
        	<span><?php echo $this->__('By ') ?><label><?php echo $post->getUser(); ?></label></span>
        	<span>
				<?php echo $this->__('On ') ?><?php echo date('F d', strtotime($post->getCreatedTime())) ?>
			</span>
        	<?php 
				  $postCats = $post->getCats();
				  
			?>
			<?php if($postCats):?>
					<?php 
			$route = Mage::getStoreConfig('blog/blog/route');
			if ($route == "") {
				$route = "blog";
			}
			$route = Mage::getUrl($route);
            $postCats = Mage::getModel('blog/cat')->getCollection()
						->addPostFilter($post->getId())
						->addStoreFilter(Mage::app()->getStore()->getId());			
			$class = '';
			if(count($postCats) > 1) ?>
			<span>
				<?php echo $this->__('In ') ?>
				<?php foreach($postCats as $cat): ?>
					<a href="<?php echo $route . "cat/" . $cat->getIdentifier();?>"><?php echo $cat->getTitle();?></a><?php echo $class;?>
				<?php endforeach;?>
			</span>
			<?php endif;?>
            <?php if ($this->getCommentsEnabled()): ?>
            	<?php if($post->getCommentCount() > 0): ?>	
					<span>
						<?php echo $post->getCommentCount(); ?>
						<a href="<?php echo $post->getAddress(); ?>#commentBox">
							<?php if ($post->getCommentCount() < 2): ?>
							<?php echo $this->__('Comment') ?>
							<?php else: ?>
								 <?php echo $this->__('Comments') ?>
							<?php endif ?>
						</a>
					</span>
                <?php endif; ?>
                
            <?php endif; ?>
            <span class="tags"><?php echo $this->getTagsHtml($post) ?></span>
        </div>
    <div class="postContent"><?php echo $post->getPostContent(); ?></div>
    <?php echo $this->getBookmarkHtml($post) ?>
</div>

<!-- Comment Section -->
<?php if ($this->getCommentsEnabled()): ?>
    <?php  $comments = $this->getComment(); ?>
    <?php if (count($comments) > 0): ?>
    <div class="comments">
		<div class="comments-title">
			<h5><?php echo $this->__(" Comments") ?></h5>
		</div>
		<div class="comments-content">
			<?php foreach ($comments as $comment) : ?>
			<div class="content">
				<!--a href="#" class="col-lg-2 col-md-2 col-sm-2 col-xs-3">
						<?php
							$dest = $post->getPostContent();
							$img = preg_match('/<img[^>]+>/i', $dest, $result);
						?>
						<?php if ($result): ?>
							<?php echo current($result); ?>
						<?php endif; ?>
				</a-->
				<!--div class="col-lg-10 col-md-10 col-sm-10 col-xs-9"-->
					<div class="media-footer">
						<span><?php echo $comment->getUser(); ?></span>
						<?php echo date('F d Y', strtotime($comment->getCreatedTime())) ?>
					</div>
					<div class="media-body">
						<p><?php echo nl2br($comment->getComment()); ?></p>
					</div>
				<!--/div-->
			</div>
			<?php endforeach; ?>
		</div>
	</div>
	<?php endif ?>
	<div class="post_contents">
		<div class="postTitle"><a name="commentBox" ></a>
			<h5><?php echo $this->__('Leave A Comments') ?></h5>
		</div>
		
		<?php if ($post->getComments()): ?>
			<div class="postError"><?php echo Mage::helper('blog')->__('Comments are Closed for this post') ?></div>
		<?php else: ?>
			<?php if ($this->getLoginRequired()): ?>
				<?php if ($this->helper('customer')->isLoggedIn()): ?>
					<form action="" id="postComment" method="post">
						<fieldset class="group-select">
							<h4 class="legend"><?php echo Mage::helper('blog')->__('Submit Comment') ?></h4>
							<div class="form-list">
								<div>

									<div class="input-box aw-blog-comment-area">
										<label for="comment" class="required"><?php echo Mage::helper('blog')->__('Comment') ?><i>*</i></label><br />
										<textarea name="comment" id="comment" title="<?php echo $this->__('Comment') ?>" class="required-entry input-text" style="height:150px;width:95%;" cols="50" rows="5"><?php echo $this->getCommentText(); ?></textarea>
									</div>
								</div>
							</div>
						</fieldset>
						<div class="button-set" style="width:96%">
							<input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
							<input name="email" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserEmail()) ?>"/>
							<input name="user" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserName()) ?>"/>
							<p class="required"><em>*</em><?php echo $this->__('Required Fields') ?></p>
							<button class="form-button button" type="submit"><span><span><?php echo Mage::helper('blog')->__('Submit Comment') ?></span></span></button>
						</div>
					</form>

					<script type="text/javascript">
						var contactForm = new VarienForm('postComment', false);
					</script>

				<?php else: ?>
					<p><?php echo Mage::helper('blog')->__('You must be logged in to post a comment.'); ?></p>
					<p><a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"><?php echo Mage::helper('blog')->__('click here'); ?></a> <?php echo Mage::helper('blog')->__('to log in'); ?></p>
				<?php endif ?>

			<?php else: ?>

				<form action="" id="postComment" method="post">
					<fieldset class="group-select">
						<div class="form-list">
							<div>
								<div class="row">
									<div class="col-lg-6 col-md-6 col-sm6">
										<div class="input-box">
											<!--label for="name" class="required"><?php echo Mage::helper('blog')->__('Name') ?><i>*</i></label-->
											<input name="user" id="user" placeholder="Name *" value="<?php echo $this->getCommentName(); ?>" title="<?php echo $this->__('Name') ?>" class="required-entry input-text" type="text" />
										</div>
			
										<div class="input-box">
											<!--label for="email" class="required"><?php echo Mage::helper('blog')->__('Email') ?><i>*</i></label-->
											<input name="email" id="email" placeholder="Email *" value="<?php echo $this->getCommentEmail(); ?>" title="<?php echo $this->__('Email') ?>" class="required-entry input-text validate-email" type="text" />
										</div>
									</div>
									<div class="col-lg-6 col-md-6 col-sm6">
										<div class="input-box aw-blog-comment-area">
											<!--label for="comment" class="required"><?php echo Mage::helper('blog')->__('Comment') ?><i>*</i></label-->
											<textarea name="comment" id="comment" placeholder="Comment *" title="<?php echo Mage::helper('blog')->__('Comment') ?>" class="required-entry input-text" style="height:150px;" cols="50" rows="5"><?php echo $this->getCommentText(); ?></textarea>
										</div>
									</div>
								</div>
							</div>

							<?php
							if (Mage::getStoreConfig('blog/recaptcha/enabled') && !$this->helper('customer')->isLoggedIn()) {
								?><div><?php
					require_once 'recaptcha/recaptchalib-aw.php';

					// Get a key from http://recaptcha.net/api/getkey
					$publickey = Mage::getStoreConfig('blog/recaptcha/publickey');
					$privatekey = Mage::getStoreConfig('blog/recaptcha/privatekey');
					$error = null;

					echo recaptcha_get_html($publickey, $error);
								?></div><?php
				}
							?>
						</div>
					</fieldset>
					<div class="button-set" style="width:96%">
						<input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
						<p class="required"><em>* </em><?php echo $this->__('Required Fields') ?></p>
						<button style="text-transform: uppercase;" class="btn btn-primary" type="submit"><span><span><?php echo Mage::helper('blog')->__('Submit') ?></span></span></button>
					</div>
				</form>

				<script type="text/javascript">
					var contactForm = new VarienForm('postComment', false);
				</script>
			<?php endif; ?>
		<?php endif; ?>
	</div>
<?php endif; ?>